### ISSUE TITLE
Could you share the training log?

### ISSUE THREAD

**Issue by serend1p1ty** [OpenDriveLab/UniAD#10]
I am training UniAD on our own dataset, but I don't know what the final value of each loss should be.

Could you share your training log? Thanks!

**Comment by YTEP-ZHI** [comment]
Please download the second-stage training log here: https://github.com/OpenDriveLab/UniAD/releases/download/v1.0/uniad_e2e_20ep_train.log

**Comment by serend1p1ty** [comment]
Thank you very much!
