### ISSUE TITLE
Model GMAC/FLOPS

### ISSUE THREAD

**Issue by ChunChenLin** [OpenDriveLab/UniAD#100]
Hello,
Do you have the model complexity numbers (e.g., GMAC or FLOPs) or is there any way that I can get the numbers?

Thanks so much.

**Comment by Yihanhu** [comment]
![image](https://github.com/OpenDriveLab/UniAD/assets/33394567/011f03c5-56f6-4fbb-a46a-8a7a90cd91a5)

**Comment by DDEONSIK** [comment]
Hello and thank you for your work.

When I look at the test results, I don't see **FLOPs** and **FPS** results, is there any way to get them?
