### ISSUE TITLE
about eval

### ISSUE THREAD

**Issue by haichen-ber** [OpenDriveLab/UniAD#103]
Thanks to the authors for their work on this paper. What is the Col. Rate (%) in Table 7 in your paper? The result I get after eval is as follows: 
+-------------+--------+--------+--------+--------+--------+--------+
|   metrics   |  0.5s  |  1.0s  |  1.5s  |  2.0s  |  2.5s  |  3.0s  |
+-------------+--------+--------+--------+--------+--------+--------+
|   obj_col   | 0.0000 | 0.0000 | 0.0002 | 0.0002 | 0.0003 | 0.0012 |
| obj_box_col | 0.0003 | 0.0005 | 0.0007 | 0.0012 | 0.0033 | 0.0060 |
|      L2     | 0.3482 | 0.5463 | 0.7742 | 1.0430 | 1.3588 | 1.7089 |
+-------------+--------+--------+--------+--------+--------+--------+
I hope you have time to guide me.

**Comment by YTEP-ZHI** [comment]
@haichen-ber  Hi, Col. Rate (%)  in the paper refers to the obj_box_col (second row) of the table. We take the value of 1s, 2s, 3s, and the average value of them (1, 2, 3s) as evaluation metrics.

**Comment by haichen-ber** [comment]
> 
ok, thanks for your guidance！

**Comment by YTEP-ZHI** [comment]
I'm closing this issue as it's resolved. Feel free to reopen it if needed.
