### ISSUE TITLE
Question about `collision_optimization` of the planning

### ISSUE THREAD

**Issue by whystopped** [OpenDriveLab/UniAD#104]
https://github.com/OpenDriveLab/UniAD/blob/489a2976201946cec33b32309680b4db514e8a62/projects/mmdet3d_plugin/uniad/dense_heads/planning_head.py#L225

why `pos_xy` calculates as `* 0.5 + 0.25`

**Comment by YTEP-ZHI** [comment]
Change the origin of coordinates of `pos_xy` from `top_left` to the `center of BEV plane`.

**Comment by whystopped** [comment]
> @whystopped Hi, it's to change the origin of coordinates of `pos_xy` from `top_left` to the `center of BEV plane`.

Thank you very much for your reply, but I still have some questions.
In my opinion, `pos_xy[:, 0] - self.bev_h//2` has completed the transformation of the origin, so what is the meaning of `* 0.5 + 0.25`?

**Comment by Yihanhu** [comment]
pos_xy is in the pixel coordinate, ` pos_xy[:, 0] = (pos_xy[:, 0] - self.bev_h//2) * 0.5 + 0.25 ` is to transform the coordinate from pixelwise to real world coordinate (meters)

**Comment by whystopped** [comment]
> pos_xy is in the pixel coordinate, `pos_xy[:, 0] = (pos_xy[:, 0] - self.bev_h//2) * 0.5 + 0.25` is to transform the coordinate from pixelwise to real world coordinate (meters)

got it, thanks very much
