### ISSUE TITLE
problem about "reference_points" update in inference.

### ISSUE THREAD

**Issue by Super-Tree** [OpenDriveLab/UniAD#105]
<img width="812" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/24618712/d3515450-735f-46a7-a0de-d64e86786013">
`active_inst.ref_pts[:,:2]` was update  twice? and it seems useless for active_inst.ref_pts[...,2], so why we need to use this function `self.reference_points`? 
Thanks in advance for your reply!

**Comment by ilnehc** [comment]
@Super-Tree Good catch. Since we have velocity prediction, we can basically update reference points with it in the `velo_update` function. But empirically it did not work well for the z axis. Thus the z value is updated by the `reference_points` layer, which has some redundant output (xy) as you found. In the meantime, the function is also used for ref_pts initialization.

**Comment by Super-Tree** [comment]
@ilnehc Got it, thanks~

**Comment by Super-Tree** [comment]
<img width="866" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/24618712/f645dac9-3ebe-49ea-9cb8-297d050fe874">

<img width="609" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/24618712/15ac5f7a-9396-4d5a-8595-c80cfabfaf30">


<img width="707" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/24618712/f7c23302-3b0c-4a00-a0cc-42059ed658db">
I have some confusion about the velo slice，
 velo = active_inst.pred_boxes[:, -2:] or velo = active_inst.pred_boxes[:, -3:-1]

**Comment by ilnehc** [comment]
@Super-Tree The comment in L214 is wrong. Some information in this function:
https://github.com/OpenDriveLab/UniAD/blob/489a2976201946cec33b32309680b4db514e8a62/projects/mmdet3d_plugin/core/bbox/util.py#L26

**Comment by Super-Tree** [comment]
okk~

**Comment by serend1p1ty** [comment]
> @Super-Tree Good catch. Since we have velocity prediction, we can basically update reference points with it in the `velo_update` function. But empirically it did not work well for the z axis. Thus the z value is updated by the `reference_points` layer, which has some redundant output (xy) as you found. In the meantime, the function is also used for ref_pts initialization.

@Super-Tree @ilnehc  UniAD only need the x-y coordinates of the reference point, and updating z seems unnecessary?
