### ISSUE TITLE
Why use 900 queries for detection and tracking?

### ISSUE THREAD

**Issue by Super-Tree** [OpenDriveLab/UniAD#106]
As I know, there aren‘t so many objects in a few second(only 300 in DETR)，so why need to set a large number of queries？I guess for better matching new detection to ground_truth due to applying plenty of queries？

**Comment by YTEP-ZHI** [comment]
It's a common technique to apply (>=) 900 queries in detection for better results. Reference:  https://arxiv.org/abs/2203.03605, https://arxiv.org/abs/2207.13085

**Comment by Super-Tree** [comment]
Got it, thanks~
