### ISSUE TITLE
Question about the config of `num_levels` of seg_head

### ISSUE THREAD

**Issue by whystopped** [OpenDriveLab/UniAD#108]
In the config of seg_head, `num_levels` is set to `4`
https://github.com/OpenDriveLab/UniAD/blob/2f38ff1357d3956af11c5609d5275db56c559c20/projects/configs/stage2_e2e/base_e2e.py#L266
https://github.com/OpenDriveLab/UniAD/blob/2f38ff1357d3956af11c5609d5275db56c559c20/projects/configs/stage2_e2e/base_e2e.py#L286
but the input of seg_head is `bev_embed`, which has no multi-scale
so, maybe `num_levels` should be set to `1`?

**Comment by YTEP-ZHI** [comment]
@whystopped. Thanks ! We will check this part of codes.

**Comment by ilnehc** [comment]
@whystopped Thanks for reporting the issue. The parameter should be `1`. But `4` basically adds more reference points in practice which does not lead to error warnings of the network structure. We tested to set it to `1` and found that this modification would greatly improve the segmentation performance and slightly improve other tasks. I will update the checkpoints and logs in the future.

**Comment by Lewis-Lu** [comment]
Checked out the same error as this ticket when trying to deploy the segmentation part.

num_levels=4 results in cpu-version MS_Deform_Atten error.

should set num_levels=1

Best,
Lewis

**Comment by ilnehc** [comment]
@Lewis-Lu Updated in https://github.com/OpenDriveLab/UniAD/releases/tag/v1.0.1.
