### ISSUE TITLE
Questions about the prepared dataset.

### ISSUE THREAD

**Issue by lzrbit** [OpenDriveLab/UniAD#109]
Hi, nice work in CVPR. I have a question about the prepared dataset. I have downloaded the processed nuscenes_infos_temporal_{train,val}.pkl.  Do I still need to download the raw nuscene dataset? Considering that the raw dataset is too large.  
Or only with nuscenes_infos_temporal_{train,val}.pkl I can successfully train and evaluate the uniAD model?
Thanks a lot.

**Comment by ilnehc** [comment]
@lzrbit No, you can't. You need the raw data including the images and some other related JSON files.

**Comment by stephenunderdog** [comment]
可以使用v1.0-mini里的数据训练吗？如何使用？
