### ISSUE TITLE
Coordinate in the motion prediction evaluation

### ISSUE THREAD

**Issue by exiawsh** [OpenDriveLab/UniAD#11]
Hello, thanks for the great work. 
I have some confusion about the coordinate for motion prediction evaluation. If I use the same evaluation code, which coordinate system should I adopt here (ego vehicle, other vehicles, or global coordinates)?
https://github.com/OpenDriveLab/UniAD/blob/e92a5513d7354a30f41e7a9379c8d023a93de9dc/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py#L826

**Comment by YTEP-ZHI** [comment]
![image](https://user-images.githubusercontent.com/48089846/232974212-6fd65413-9982-44d6-bb76-ec4f3f41aae1.png)

Thanks for your interest. The motion gts are all in **lidar coordinate**, the same as 3d **gt_bboxes**.

**Comment by exiawsh** [comment]
So the network output trajectory should be in the lidar coordinate of other vehicles, is that right?
https://github.com/OpenDriveLab/UniAD/blob/e92a5513d7354a30f41e7a9379c8d023a93de9dc/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py#L811
Is the operation here to transform the trajectory (in other vehilce lidar) back to the ego lidar coordinate?

**Comment by exiawsh** [comment]
> ![image](https://user-images.githubusercontent.com/48089846/232974212-6fd65413-9982-44d6-bb76-ec4f3f41aae1.png)
> 
> Thanks for your interest. The motion gts are all in **lidar coordinate**, the same as 3d **gt_bboxes**.



I think my understanding above is correct. Thank you!
