### ISSUE TITLE
sdc_track_boxes data meaning?

### ISSUE THREAD

**Issue by TonyPeng-2018** [OpenDriveLab/UniAD#111]
Hello, I saw the data in the sdc_track_boxes is [LiDARInstance3DBoxes(tensor([[ 0.0165,  0.0088, -0.7786,  1.7302,  4.0819,  1.5589, -3.1414,  0.0671, 8.0454]], grad_fn=<CloneBackward>)), tensor([0.3953]), tensor([0]), tensor([0]), tensor([True])]. Could someone tell me what they are meaning? Thanks.

**Comment by Yihanhu** [comment]
Hi @TonyPeng-2018 ,
That's the track box for ego vehicle query.

**Comment by TonyPeng-2018** [comment]
@Yihanhu Hello. Thanks. Could you tell me how this query is built? I saw that the default LiDARInstance3DBoxes has 7 dimensions, so what other dimensions meaning are?

**Comment by YTEP-ZHI** [comment]
@TonyPeng-2018 You can see the definition of each dimension of the LiDARInstance3DBoxes here (from mmdet3d repo):   https://github.com/open-mmlab/mmdetection3d/blob/fe25f7a51d36e3702f961e198894580d83c4387b/mmdet3d/structures/bbox_3d/lidar_box3d.py#L33-L34
