### ISSUE TITLE
Are you trying to deploy this project to the car? Is it possible to use the camera input directly to produce the result in real time?

### ISSUE THREAD

**Issue by PlutoXN** [OpenDriveLab/UniAD#113]
Are you trying to deploy this project to the car? Is it possible to use the camera input directly to produce the result in real time?

**Comment by ilnehc** [comment]
@PlutoXN Thanks for your question. 1. We do not have a real car for deployment. 2. It is possible but it involves some engineering efforts. It also takes calibration information as one of the inputs.
