### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by hjfenghj** [OpenDriveLab/UniAD#114]
hello,thanks for your work firstly.I met an issue which don't confluence the project but I can't understand it. If I use "wegt" to download the model pth,the project correctly work.but if I download the model pth from the Google Chrome web page,i met the follow question.
![1234](https://github.com/OpenDriveLab/UniAD/assets/72334253/77c938b4-b4b4-471b-a215-46c485040461)

` File "/home/hjfeng/anaconda3/envs/Uniad/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 270, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/hjfeng/anaconda3/envs/Uniad/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/hjfeng/anaconda3/envs/Uniad/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
/home/hjfeng/anaconda3/envs/Uniad/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2462241) of binary: /home/hjfeng/anaconda3/envs/Uniad/bin/python
Traceback (most recent call last):
`
 
Do you know why this problem occurs?

**Comment by ilnehc** [comment]
@hjfenghj It is possible that your downloaded file is corrupted. You can try to delete and re-download.

**Comment by hjfenghj** [comment]
@ilnehc thank you！you are right
