### ISSUE TITLE
TypeError: UniAD: BEVFormerTrackHead: PerceptionTransformer: __init__() got an unexpected keyword argument 'bev_feat_no_grad'

### ISSUE THREAD

**Issue by dikubab** [OpenDriveLab/UniAD#12]
While evaluting your pretrained model the following error message generated. 
TypeError: UniAD: BEVFormerTrackHead: PerceptionTransformer: __init__() got an unexpected keyword argument 'bev_feat_no_grad'
![image](https://user-images.githubusercontent.com/60455687/233831545-c0beedf5-3a0e-475c-ac36-24f281634d32.png)

**Comment by YTEP-ZHI** [comment]
![image](https://user-images.githubusercontent.com/48089846/233835016-d23cd585-5c6d-41a7-a0e0-a63831f5f0be.png)
Hi, could you please `git pull` or simply delete this line in config? It should be working after deleting.

**Comment by dikubab** [comment]
Thank you for your promt response the problem is solved.
