### ISSUE TITLE
python path in miniconda that causes No module named torch.distributed

### ISSUE THREAD

**Issue by bzha5848** [OpenDriveLab/UniAD#120]
Hello there,
Thanks for the help last time!! But I'm still having issues with python. When I run the sample it shows me the error below.
![image](https://github.com/OpenDriveLab/UniAD/assets/49177682/f3012399-f6c9-498d-b4c4-b7688bf241cf)
But when I check the python path I'm using in miniconda it gives me like that.
![image](https://github.com/OpenDriveLab/UniAD/assets/49177682/2b36a7ec-621e-4995-8042-ec718c6377e0)
Just wondering how can I modify ?

Thanks so much!!

**Comment by ilnehc** [comment]
@bzha5848 I think the `sudo` command results in using the default python.

**Comment by bzha5848** [comment]
Without sudo, I met these errors:

ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
/home/tianyu/miniconda3/envs/uniad2/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 166580) of binary: /home/tianyu/miniconda3/envs/uniad2/bin/python

I'm pretty sure I follow the instruction in Install.md, but I don't understand where's the problem from.

**Comment by bzha5848** [comment]
I solved error 
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0

But still have the issue
ImportError: numpy.core.multiarray failed to import
/home/tianyu/miniconda3/envs/uniad2/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 169057) of binary: /home/tianyu/miniconda3/envs/uniad2/bin/python

I've checked the numpy version, which is 1.20.0, and modified the numpy in mmdet3d as the same, but I'm still having this issue. I can't understand what's happening.

**Comment by bzha5848** [comment]
Okay, I manage to solve numpy issues with numpy==1.23.5. I guess it might be weird for requirements setting. As For some components we need numpy==1.20.0. It might be a good question to ask.

**Comment by yudefu** [comment]
其实可以不用在conda环境安装uniad所需要的环境，只要安装install里面需要的torch、cuda相关的版本，后面随便安装mmcv等包就可以，你可以试一下
