### ISSUE TITLE
Is there a typo in `create_data.py`?

### ISSUE THREAD

**Issue by zhyzhyzhy123** [OpenDriveLab/UniAD#122]
When I read through the code, I found in the line 75, the argument of `--out-dir`, the parameter `required` is `'False'` not `False`. Is this a typo or a trick on purpose?

**Comment by ilnehc** [comment]
@zhyzhyzhy123 Thanks. It is a typo.

**Comment by YTEP-ZHI** [comment]
@zhyzhyzhy123 Resolved, thanks.
