### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by dikubab** [OpenDriveLab/UniAD#13]
The is may be a bug in the code. I tried to figure out. But I could not find it. The path to image looks like broken. 
 FileNotFoundError: img file does not exist: data/nuscenes/./data/nuscenes/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151603512404.jpg

![image](https://user-images.githubusercontent.com/60455687/233883436-6fc3aec6-1beb-4612-8ced-3e61bb529e9a.png)

**Comment by YTEP-ZHI** [comment]
Hi @dikubab. Seems like the `data/nuscenes` is duplicated. Did you place the dataset in the right place as is described in  https://github.com/OpenDriveLab/UniAD/blob/main/docs/DATA_PREP.md? 
![image](https://user-images.githubusercontent.com/48089846/233891873-570ea9c9-4a8e-43fc-9dd2-8cc17b9bda39.png)

**Comment by dikubab** [comment]
Yes, I did in the same way. There is no duplication.

**Comment by YTEP-ZHI** [comment]
I'm checking on this and will notice you once it's resolved.

**Comment by YTEP-ZHI** [comment]
Hi @dikubab , I cannot reproduce the error. It works well  using extractly the same codes and data_info in this repo.
![image](https://user-images.githubusercontent.com/48089846/233973597-dc19d5ed-7f0b-45db-be8f-20bdc8b244d1.png)

**Comment by dikubab** [comment]
The problem is fixed by readjusting  /projects/configs/stage1_track_map/base_track_map.py line 419  img_root= 'data_root' to  img_root= ""

![image](https://user-images.githubusercontent.com/60455687/233895919-329a766d-c6c0-411b-a44e-8fb06b0203a9.png)

**Comment by PengLiangwf** [comment]
Thanks. I came across the same issue.
![issue](https://github.com/OpenDriveLab/UniAD/assets/91534615/0258e1f0-5b7b-4e1d-822a-b6bb1b1a8f83)

**Comment by Super-Tree** [comment]
<img width="1127" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/24618712/9b497c2e-8ab7-410d-8fd4-28d175816214">

**Comment by Cyanglll** [comment]
> I came across the same issue too when I used v1.0-mini dataset. However it works well when use v1.0 instead. so I try to find the difference between v1.0 pkls which is pre-generated and v1.0-mini pkls generated by 'uniad_create_data.sh'. Here is the diff: when in v1.0 pkls, camera path is like that: `samples/CAM_FRONT/n015-2018-08-02-17-16-37+0800__CAM_FRONT__1533201470412460.jpg` when in v1.0-mini pkls generated by 'uniad_create_data.sh', the camera path is like that: `./data/nuscenes/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151603512404.jpg`
> 
> So,I think there maybe bugs in uniad_create_data for v1.0-mini. @YTEP-ZHI @dikubab @PengLian

> I came across the same issue too when I used v1.0-mini dataset. However it works well when use v1.0 instead. so I try to find the difference between v1.0 pkls which is pre-generated and v1.0-mini pkls generated by 'uniad_create_data.sh'. Here is the diff: when in v1.0 pkls, camera path is like that: `samples/CAM_FRONT/n015-2018-08-02-17-16-37+0800__CAM_FRONT__1533201470412460.jpg` when in v1.0-mini pkls generated by 'uniad_create_data.sh', the camera path is like that: `./data/nuscenes/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151603512404.jpg`
> 
> So,I think there maybe bugs in uniad_create_data for v1.0-mini. @YTEP-ZHI @dikubab @PengLiangwf

Can you publish a tutorial that uses v1.0-mini? Where should the data be downloaded, how to use bash commands, and how to  change the data_root to empty in config files?Thank you ery much！@YTEP-ZHI @dikubab @PengLiangwf

**Comment by Cyanglll** [comment]
Can you publish a tutorial that uses v1.0-mini? Where should the data be downloaded, how to use bash commands, and how to change the data_root to empty in config files?Thank you ery much！@YTEP-ZHI @dikubab @PengLiangwf

**Comment by pily1** [comment]
when use mini datasets for inference,in the  UniAD/projects/mmdet3d_plugin/datasets/pipelines/loading.py file,at 48 line,comment out the code
from img_path = os.path.join(self.img_root,img_path)
to #img_path = os.path.join(self.img_root,img_path)
it solved the path problem

**Comment by MuHeDing** [comment]
> when use mini datasets for inference,in the UniAD/projects/mmdet3d_plugin/datasets/pipelines/loading.py file,at 48 line,comment out the code from img_path = os.path.join(self.img_root,img_path) to #img_path = os.path.join(self.img_root,img_path) it solved the path problem

Very good answers！It worked！
