### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by ZayneLeo** [OpenDriveLab/UniAD#130]
![2157026f404680279a6c74d66eb74f8](https://github.com/OpenDriveLab/UniAD/assets/99701420/f7c9388a-b9f0-4364-b387-ef1e34b280c5)
How do I generate RESULT.pkl?
Thank you!

**Comment by yudefu** [comment]
参考这个问题：https://github.com/OpenDriveLab/UniAD/issues/71；直接利用推理的结果进行可视化，并且可视化需要利用第二阶段的结果；执行脚本自己参考71，或者看https://github.com/OpenDriveLab/UniAD/blob/main/docs/TRAIN_EVAL.md，将stage1换成stage2的配置文件
