### ISSUE TITLE
Visualize Attention Mask

### ISSUE THREAD

**Issue by sdelcore** [OpenDriveLab/UniAD#134]
Hi, thanks for the great work. I was wondering how it would be possible to generate the visualization for the attention mask? In the visualization script, I have found the following function: https://github.com/OpenDriveLab/UniAD/blob/main/tools/analysis_tools/visualize/render/bev_render.py#L198

I'm assuming I need to add it to the draw over the hd map? and find a variable to fulfill the `predicted_planning.attn_mask`? Is this the `plan_query` variable from the following issue https://github.com/OpenDriveLab/UniAD/issues/78?

Thanks in advance!

**Comment by Yihanhu** [comment]
Hi @sdelcore 
Yes, you should dump the attention masks overhere:
https://github.com/OpenDriveLab/UniAD/blob/main/projects/mmdet3d_plugin/uniad/dense_heads/planning_head.py#L188C27-L188C38

**Comment by hanbrianlee** [comment]
Hi @Yihanhu ,  so I have to basically get the attention scores from within the self.attn_module right?
Is there any reason why such vis helper codes are omitted? or are they just not pushed yet? (due to cleaning up etc)

Thanks!

**Comment by Yihanhu** [comment]
Hi @hanbrianlee, You're absolutely right – get attn mask can make the code a bit messy. So, I cleaned it up since you can easily obtain them from self.attn_module.

**Comment by sdelcore** [comment]
Thanks! For anyone looking into this too. I had to create my own child class for TransformerDecoderLayer which follows forward() of the original torch class, except that it returns the attention weights in addition to the output. I had to use this new class for the planning module. These weights were of shape [1,1,40000] which I could reshape to 200,200 and normalize to visualize the attention mask

**Comment by DDEONSIK** [comment]
> Thanks! For anyone looking into this too. I had to create my own child class for TransformerDecoderLayer which follows forward() of the original torch class, except that it returns the attention weights in addition to the output. I had to use this new class for the planning module. These weights were of shape [1,1,40000] which I could reshape to 200,200 and normalize to visualize the attention mask

Do you mind if I ask for a little more detail, I'm curious what files you used and what code you used.
