### ISSUE TITLE
Cannot reproduce planning performance

### ISSUE THREAD

**Issue by nanxiangshui** [OpenDriveLab/UniAD#135]
Hi there,

I was trying to build my e2e network based on your code. But I cannot reproduce the planning performance reported in your paper, using your code, on nuScence. In my experiments, the L2 loss is larger.

Do you have a special training method for the planning module?

Thanks.

**Comment by Yihanhu** [comment]
Hi @nanxiangshui , can you share more details about your training, as well as your current metrics?
