### ISSUE TITLE
Questions about cumsum trick in motion prediction.

### ISSUE THREAD

**Issue by dingli-dean** [OpenDriveLab/UniAD#140]
Hi team, thanks for releasing this awesome codebase. 
In MotionFormer, torch.cumsum() is applied to the output of traj_reg_branches. Is this cumsum trick responsible for the maintaining the learning stability of traj_reg_branch?
If we use the same process as detection, i.e. tmp[..., :2] += reference_trajs, will this defect the performance of motion prediction?
Thx.

**Comment by Yihanhu** [comment]
Hi @dingli-dean, yes, the cumsum trick could slightly improve the result.
