### ISSUE TITLE
How to calculate the hardcoded parameters

### ISSUE THREAD

**Issue by Jian-danai** [OpenDriveLab/UniAD#149]
occflow_grid_conf = {
    'xbound': [-50.0, 50.0, 0.5],
    'ybound': [-50.0, 50.0, 0.5],
    'zbound': [-10.0, 10.0, 20.0],
}
what does -50, 50,5, -10, 10, 20 means?

**Comment by YTEP-ZHI** [comment]
Hi @Jian-danai, this is the BEV range (for the x, y, and z axes). Objects beyond this range are not considered in training and testing. 

Take xbound as an example, [-50, 50, 0.5] stands for the left limit, right limit, and the resolution for each bev grid (0.5 = 50 m / 100 grid).  

We set `occflow_grid_conf` different from `bevformer_bev_conf` to align the setting with other occupancy research (e.g., fiery and BEVerse) for fair comparison.
