### ISSUE TITLE
Training on RTX 4090

### ISSUE THREAD

**Issue by Dylan-LDR** [OpenDriveLab/UniAD#15]
Hi, thanks for the great work. However, I find it difficult to correctly train the e2e model on 8 RTX 4090 GPUs, which is troubled by NCCL errors and cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR. Can you provide some supports or examples? Thank you.

**Comment by YTEP-ZHI** [comment]
Could you provide more information about this error? Such as when did it happen (in data loading or model training)? A screenshot of the full error message would be recommended.

**Comment by Dylan-LDR** [comment]
Thanks for the quick reply. First we met the problem of NCCL as
![image](https://user-images.githubusercontent.com/49780695/234752248-1de0f2ee-68f9-49e5-b34d-1700fa7cd72f.png)
When we try to solve the NCCL problem using options ```export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1```, we get errors like:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/49780695/234751993-9645c576-2681-471d-bd5d-1d8675f5dd07.png">
It seems that the CUDA and pyTorch versions conflict causes this.

**Comment by YTEP-ZHI** [comment]
Yes, I think so. You should try switch to a CUDA version which is compatible with torch 1.9.1.

**Comment by Dylan-LDR** [comment]
But the environment we are using is suitable for A100 GPUs. Our CUDA version is 11.1,
![image](https://user-images.githubusercontent.com/49780695/234755955-dc977dcc-3ac0-4be6-943e-34d13765c279.png)
which should be compatible with torch 1.9.1.

**Comment by YTEP-ZHI** [comment]
Let's see what chatGPT is suggesting:
![image](https://user-images.githubusercontent.com/48089846/234760765-6ce6aa18-cbca-4ed2-bf15-7e1d7148765b.png)

**Comment by Little-Podi** [comment]
May I ask does RTX 4090 GPU support multi-GPU training? I heard that Nvidia removes NVLink in 40 series and I didn't buy a RTX 4090 multi-GPU server due to this concern.

**Comment by YTEP-ZHI** [comment]
Hi @Dylan-LDR @Little-Podi. I'm afraid I cannot provide you with any helpful information on the usage of RTX 4090. Our program could be successfully running on NVIDIA V100 and A100. Maybe you should reach out to the community of RTX 4090. Still, all of your comments are appreciated.

**Comment by YTEP-ZHI** [comment]
It's probably caused by limited memory. Please refer to this issue: https://github.com/OpenDriveLab/UniAD/issues/41

**Comment by vgudapati** [comment]
I'm seeing the same issue with both V100 (AWS EC2 p3dn with 8 V100's with 32GB VRAM each) and A10 (AWS g5-48x EC2 instance with 24GB VRAM each). Stage 2 training fails exactly after 4 epochs during validation. Anybody observing similar errors?

**Comment by duanmushuangquan** [comment]
similar errors , Have you solved the problem？

**Comment by jagdishbhanushali** [comment]
I also had same error while running eval on 2 [GPUs](https://github.com/OpenDriveLab/UniAD/issues/229#issuecomment-2859947064) . 
Please refer solution provided by Tonny24Wang(https://github.com/OpenDriveLab/UniAD/issues/229#issuecomment-2864958854), (https://github.com/OpenDriveLab/UniAD/issues/229#issuecomment-2869145791)
