### ISSUE TITLE
Dataparsers for other datasets

### ISSUE THREAD

**Issue by wljungbergh** [OpenDriveLab/UniAD#151]
Hi, 

Thank you for your work.

Would you happen to know of any efforts to implement data parsers for other datasets like Argoverse 2, WOD, or ZOD?

**Comment by YTEP-ZHI** [comment]
@wljungbergh There are no off-the-shelf data parsers for other AV datasets. It will take a lot of engineering effort to adapt the codebase to other datasets, as it's heavily coupled with nuscenes annotations for multiple tasks throughout the data process, training, inference/validation.

**Comment by wljungbergh** [comment]
Alright! Might create one and add a PR. Thanks

**Comment by justeWang** [comment]
> Alright! Might create one and add a PR. Thanks

您好，请问您找到解决办法了吗？我正在尝试使用其他数据集和接入carla仿真器，请问您可以给一些建议吗？谢谢
Hello, have you found a solution? I am trying to use other data sets and access the carla emulator, can you give me some advice? thank you

**Comment by Rookie-From-East** [comment]
> > Alright! Might create one and add a PR. Thanks
> 
> 您好，请问您找到解决办法了吗？我正在尝试使用其他数据集和接入carla仿真器，请问您可以给一些建议吗？谢谢 Hello, have you found a solution? I am trying to use other data sets and access the carla emulator, can you give me some advice? thank you

请问您是否成功了呢？能否分享你的做法？谢谢！
May I ask if you have succeeded? Can you share your approach? thank you!
