### ISSUE TITLE
Question about eval results

### ISSUE THREAD

**Issue by godkaieethu** [OpenDriveLab/UniAD#157]
Thank you for your excellent work.

I follow the steps in train_eval.md

for eval examples(using ckpt this work provided),i got the correct result Amota 0.390.
![评估·](https://github.com/OpenDriveLab/UniAD/assets/37395325/ab40c74e-3160-4451-9c5b-3893ef82cdf0)
But after i trained the stage one model and used the ckpt generated to eval, i only got amota 0.373.Is any thing wrong?
![训练-评估-stage1](https://github.com/OpenDriveLab/UniAD/assets/37395325/7229711f-fb15-4114-a4b6-cf48bf15cb1a)

**Comment by godkaieethu** [comment]
my train process is followed this command:
./tools/uniad_dist_train.sh ./projects/configs/stage1_track_map/base_track_map.py 8 
on 8 * A100 80G GPUS

**Comment by ilnehc** [comment]
@godkaieethu Probably due to GPU numbers. See log here: https://github.com/OpenDriveLab/UniAD/issues/21#issuecomment-1586549953.

**Comment by godkaieethu** [comment]
> @godkaieethu Probably due to GPU numbers. See log here: [#21 (comment)](https://github.com/OpenDriveLab/UniAD/issues/21#issuecomment-1586549953).

I did my train on 8 A100 80G GPUS and i did not modify the config.here is my train log:

**Comment by godkaieethu** [comment]
> @godkaieethu Probably due to GPU numbers. See log here: [#21 (comment)](https://github.com/OpenDriveLab/UniAD/issues/21#issuecomment-1586549953).

thank you for your reply. According to your log in https://github.com/OpenDriveLab/UniAD/issues/21#issuecomment-1586549953. ,was the 0.393 result got on 16 GPUS? I did my train on 8 gpus ,maybe it  is the reason for the difference

**Comment by ilnehc** [comment]
@godkaieethu Yes. This will make a difference.
