### ISSUE TITLE
Why is the queue_length set to 5 and 3

### ISSUE THREAD

**Issue by shenyinzhe** [OpenDriveLab/UniAD#169]
Hello,

In the stage 1, queue_length = 5
In the stage 2, queue_length = 3
I'm wondering is there any specific reason to set it like above. 
Especially in the stage 2:
- Why is it reduced
- Why not follow nuscenes prediction challenge, where it utilizes 2 seconds past, i.e., 4 past timesteps.

Thanks

**Comment by YTEP-ZHI** [comment]
Hi @shenyinzhe, the queue length is reduced in the second stage for efficiency concerns, since a long queue of historical features is extremely memory-consuming.

**Comment by YTEP-ZHI** [comment]
The choice of queue_length=3 is more of an empirical practice, as there's no significant performance gap between queue_length 3 and 4. Therefore, we opt for queue_length=3 as it's more efficient in training.

**Comment by shenyinzhe** [comment]
Thanks for reply, I'll close the issue.
