### ISSUE TITLE
How to process nuScenes Dataset for UniAD

### ISSUE THREAD

**Issue by haibao-yu** [OpenDriveLab/UniAD#17]
Hi, thanks for your great work! I want to know how to process the nuScenes data for UniAD. Since when I evaluate the model as your guidance, there is a error as followings.
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/19658242/235341175-53f6b1bb-5aab-4d20-b4ea-7c6c7ffca651.png">

I directly used the nuScenes dataset as following settings
```
ann_file_train=data_root + f"nuscenes_infos_train.pkl"
ann_file_val=data_root + f"nuscenes_infos_val.pkl"
ann_file_test=data_root + f"nuscenes_infos_val.pkl"
```
instead of your dataset setting
```
ann_file_train=info_root + f"nuscenes_infos_temporal_train.pkl"
ann_file_val=info_root + f"nuscenes_infos_temporal_val.pkl"
ann_file_test=info_root + f"nuscenes_infos_temporal_val.pkl"
```

Hope to receive your feedback!

**Comment by haibao-yu** [comment]
Sorry, I has found the file in https://github.com/OpenDriveLab/UniAD/blob/main/docs/DATA_PREP.md and https://github.com/OpenDriveLab/UniAD/blob/main/tools/uniad_create_data.sh. However, the code lacks tools/data_converter/nuscenes_converter.py.

**Comment by chasleslr** [comment]
I also ran into a similar issue. What I did is download the `v1.0-mini` dataset from nuScenes and recreated the infos using `./tools/uniad_create_data.sh`. You have to rename the file `tools/data_converter/uniad_nuscenes_converter.py` to `tools/data_converter/nuscenes_converter.py`...

**Comment by TonyPeng-2018** [comment]
> I also ran into a similar issue. What I did is download the `v1.0-mini` dataset from nuScenes and recreated the infos using `./tools/uniad_create_data.sh`. You have to rename the file `tools/data_converter/uniad_nuscenes_converter.py` to `tools/data_converter/nuscenes_converter.py` as it seems like it was incorrectly renamed at some point.

Hello, I am not familiar with nuScenes. Could you give me some guides on how to use v1.0-mini dataset to recreate the infos folder? Thanks.
