### ISSUE TITLE
E2E checkpoint

### ISSUE THREAD

**Issue by haibao-yu** [OpenDriveLab/UniAD#18]
Thanks for your great work! I wonder to know when you will release the e2e checkpoint for the projects/configs/stage2_e2e/base_e2e.py?

**Comment by haibao-yu** [comment]
I has found it.

**Comment by haibao-yu** [comment]
> I has found it.

However, there is inference error as followings png. Maybe you should provide more sufficient files.
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/19658242/235360439-827c237b-e97e-447f-9141-8a3bbf8477a4.png">

**Comment by chasleslr** [comment]
In their [instructions](https://github.com/OpenDriveLab/UniAD/blob/main/docs/DATA_PREP.md#:~:text=Prepare%20Motion%20Anchors), the file to download is called `motion_anchor_infos_mode6.pkl`, but the file name in the code is `anchor_infos_mode6.pkl`. I've renamed the file to `anchor_infos_mode6.pkl` and it seems to work. I've been trying to run the inference pipeline and there has been a few of those issues so far.

**Comment by haibao-yu** [comment]
> In their [instructions](https://github.com/OpenDriveLab/UniAD/blob/main/docs/DATA_PREP.md#:~:text=Prepare%20Motion%20Anchors), the file to download is called `motion_anchor_infos_mode6.pkl`, but the code expects this file name: `anchor_infos_mode6.pkl`. I've renamed the file to `anchor_infos_mode6.pkl` and it seems to work. I've been trying to run the inference pipeline and there has been a few of those issues so far.

Very thanks.

**Comment by chasleslr** [comment]
@haibao-yu I would be curious to know if you can get the e2e pipeline working and get outputs for the Motion, Occupancy, and Planner. I can get the e2e inference pipeline running, but it seems like it just outputs results for Track.

**Comment by haibao-yu** [comment]
> 

I have run the whole evaluation pipeline successfully and am waiting for the results. I think you can check if you add the eval mode in config or if with these modules ( Motion, Occupancy, and Planner)  open.

**Comment by YTEP-ZHI** [comment]
@haibao-yu @chasleslr Thanks for these comments, I'm fixing these problems right now.

**Comment by YTEP-ZHI** [comment]
Hi @haibao-yu @chasleslr , sorry for the inconvenience. Please pull the newest code which I tested locally, and I think these problems are resolved. Feel free to report any other issue of this repo. Thanks again for you comments!
