### ISSUE TITLE
GPU memory is not released after training process is stopped

### ISSUE THREAD

**Issue by thunguyenth** [OpenDriveLab/UniAD#180]
Hi, thank you for sharing your work ^^
I have a problem that: 
### The GPU memory is not released if I forcibly stop the training process (by using Ctrl-C in the terminal)

 **_Config_**: 
    - Ubuntu: 20.04 LTS
    - GPU: Geforce RTX 3090 (24GB)
    - CUDA: 11.1
    - Nvidia driver: 470.239.06

**_Actions_**:

**Step 1. Training the stage 2 on the nuScene dataset _**v1.0-mini**_ version**
  ```bash
  ./tools/uniad_dist_train.sh ./projects/configs/stage2_e2e/base_e2e.py 1
   ```
**=>** _The training process is working normally_

**Step 2. Stop the training after a few iterations of the 1st epoch by using Ctrl-C in the terminal**

**Step 3. Re-run the training in step 1**
**=>** _Out of memory ERROR!!!_

I checked the GPU state by _nvidia-smi_ as shown in the below screenshot (when the training was already stopped a few minutes ago), the GPU memory used in the training process at **Step 1** was not released (17323MiB / 24259MiB).

This issue can be easily solved by releasing the GPU memory manually, but **_I wonder if this issue happens to everyone or if it just happens in my case?_** (since I couldn't find a similar issue reported in this repo) and **_Why is the GPU memory not released even though the training has stopped?_**
I would appreciate it if you could help me clarify this.

Best regards.

![image](https://github.com/OpenDriveLab/UniAD/assets/56628953/42155f5e-c87d-4a15-a588-a84132794643)

**Comment by YTEP-ZHI** [comment]
To terminate the process in Linux, you can use the command `pkill -9 python`.

**Comment by thunguyenth** [comment]
Thank you, @YTEP-ZHI, for your reply ^^

I would appreciate it if someone could explain why the GPU memory is not released after the training is stopped forcibly.
