### ISSUE TITLE
A problem: "The model and loaded state dict do not match exactly", when I try to run the "Evaluation Example".

### ISSUE THREAD

**Issue by Rango-T10000** [OpenDriveLab/UniAD#191]
Hello, I have prepared the environment and the nuScenes dataset according to your instruction.
However, when I try to evaluate the pre-trained first-stage(track_map) model as your instruction:
`./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 3`

I met a problem that says: The model and loaded state dict do not match exactly!
It seems too many parameters' state dict mismatchs the model:"uniad_base_track_map.pth" because something is upgraded to version 2.

<img width="1255" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/89722605/0e3ea813-25bf-4ac4-912d-89470147fdcc">
<img width="1444" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/89722605/5bbc4e02-274e-49ae-9bb3-ec37d05b40b3">
<img width="1459" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/89722605/d8f4d551-969a-4b6d-b4a0-bda8a4cc0fbc">
<img width="1458" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/89722605/f4fda497-3108-4d80-b0b7-4d2a8aa882d8">

I really need your help. Really thanks.

**Comment by z1433223** [comment]
Hi @Rango-T10000 I found a solution for the same problem by replacing `self.class_names = self.class_range.keys()` with `self.class_names = list(self.class_range.keys())` in python3.8/site-packages/nuscenes/eval/detection/data_classes.py, which is from this [article](https://blog.csdn.net/XCCCCZ/article/details/134295931?spm=1001.2014.3001.5501).

**Comment by Rango-T10000** [comment]
https://blog.csdn.net/h904798869/article/details/138255214

**Comment by Rango-T10000** [comment]
> Hi @Rango-T10000 I found a solution for the same problem by replacing `self.class_names = self.class_range.keys()` with `self.class_names = list(self.class_range.keys())` in python3.8/site-packages/nuscenes/eval/detection/data_classes.py, which is from this [article](https://blog.csdn.net/XCCCCZ/article/details/134295931?spm=1001.2014.3001.5501).

Hi, thanks for your reply. However, my error is: "The model and loaded state dict do not match exactly", when I run:"./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 1"

And I can't find a file in python3.8/site-packages/nuscenes/eval/detection/data_classes.py

**Comment by YTEP-ZHI** [comment]
Hi @Rango-T10000, you can ignore the warning of mismatched keys, it won't lead to any trouble. In your case, the error comes from the dataset, not the model. It seems that something's wrong in your dataset preparation.
<img width="912" alt="image" src="https://github.com/OpenDriveLab/UniAD/assets/48089846/bc257ba8-1cce-4ba9-a596-81e71b0472fa">

**Comment by Rango-T10000** [comment]
> Hi @Rango-T10000, you can ignore the warning of mismatched keys, it won't lead to any trouble. In your case, the error comes from the dataset, not the model. It seems that something's wrong in your dataset preparation. <img alt="image" width="912" src="https://private-user-images.githubusercontent.com/48089846/344883809-bc257ba8-1cce-4ba9-a596-81e71b0472fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTcyNjEsIm5iZiI6MTcxOTg5Njk2MSwicGF0aCI6Ii80ODA4OTg0Ni8zNDQ4ODM4MDktYmMyNTdiYTgtMWNjZS00YmE5LWE1OTYtODFlNzFiMDQ3MmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA1MDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNmIxZDc2NzliMTVmNDMwMWEwNWQxZmIzNzBmMDAzYWFjYjMyNjFhYTM4Njg4ZTc5ZmIzMTgzZGVkZGI0MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SleuxYeovZhnsp9SQF9fKubQ2DNsiat1977IFkLSFnc">

Thanks for your reply. Because I use the mini version dataset so there is something wrong.
And when I download the whole version of the dataset, I still met this "The model and loaded state dict do not match exactly" error. 

Accordind to your reply, I will ingore it and test again.
Really thanks for your reply.

**Comment by Rango-T10000** [comment]
> Hi @Rango-T10000, you can ignore the warning of mismatched keys, it won't lead to any trouble. In your case, the error comes from the dataset, not the model. It seems that something's wrong in your dataset preparation. <img alt="image" width="912" src="https://private-user-images.githubusercontent.com/48089846/344883809-bc257ba8-1cce-4ba9-a596-81e71b0472fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjYyNjcsIm5iZiI6MTcyMDc2NTk2NywicGF0aCI6Ii80ODA4OTg0Ni8zNDQ4ODM4MDktYmMyNTdiYTgtMWNjZS00YmE5LWE1OTYtODFlNzFiMDQ3MmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA2MzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjA0MzdlZjBiOWZhY2RhYmIwNzI5OGM4ZmJkOWZhNGZlZmU2YzE0NjJmMDUzMTcwNTcwNGJhOTQwOTQyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IOoOS3_vEwDNifqsPGy-9Fjv9rmx7sfpJTuJ7UWvKbU">


Dear author, I have run this eval command"./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 1" successfully!

However, after running the output result, there are something else warning stuff. Can you explain is anything wrong with my operation?
<img width="1671" alt="image" src="https://github.com/user-attachments/assets/a1022a1c-c855-43a2-8295-171b82e63f02">

**Comment by Rango-T10000** [comment]
> Hi @Rango-T10000, you can ignore the warning of mismatched keys, it won't lead to any trouble. In your case, the error comes from the dataset, not the model. It seems that something's wrong in your dataset preparation. <img alt="image" width="912" src="https://private-user-images.githubusercontent.com/48089846/344883809-bc257ba8-1cce-4ba9-a596-81e71b0472fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjYyNjcsIm5iZiI6MTcyMDc2NTk2NywicGF0aCI6Ii80ODA4OTg0Ni8zNDQ4ODM4MDktYmMyNTdiYTgtMWNjZS00YmE5LWE1OTYtODFlNzFiMDQ3MmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA2MzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjA0MzdlZjBiOWZhY2RhYmIwNzI5OGM4ZmJkOWZhNGZlZmU2YzE0NjJmMDUzMTcwNTcwNGJhOTQwOTQyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IOoOS3_vEwDNifqsPGy-9Fjv9rmx7sfpJTuJ7UWvKbU">
