### ISSUE TITLE
How should we interpret the output of the Planner?

### ISSUE THREAD

**Issue by chasleslr** [OpenDriveLab/UniAD#20]
Hi,

I'll start off by saying; amazing work on model! I've been exploring it and have been really impressed.

I'm trying to replicate your results, mainly the visualization on the README, and have succeeded for all modules except the Planner. I'm not sure how to interpret the outputs, mainly how to transform them to the bird's eye view.

Specifically, I've gotten the following output for the `planning_traj` key for the first frame of the `results.pkl` when running inference on the `v1.0-mini` dataset.

```python
array([[ 0.11929719,  2.7894588 ],
       [ 0.34095547,  5.5962896 ],
       [ 0.86797214,  8.415201  ],
       [ 1.6254576 , 11.165663  ],
       [ 2.505731  , 13.961164  ],
       [ 3.6870646 , 16.615181  ]], dtype=float32)
```
This appears to form a line which I'm assuming is the predicted trajectory, but I haven't found what transformation to apply to project it on the bird's eye view output by the Map, Motion, and Occupancy modules. Would you be able to point me in the right direction?

Thanks!

**Comment by dorucia** [comment]
Could you share your visualization script?

**Comment by YTEP-ZHI** [comment]
Hi @chasleslr, the output trajectory is already in the lidar coordinate of ego-car, which is the same coordinate of the BEV visualization.
![image](https://user-images.githubusercontent.com/48089846/236372625-f14cfdf4-7c75-4dee-b2e7-0de77a690c59.png)
![image](https://user-images.githubusercontent.com/48089846/236372772-f35252c4-1ee2-4684-bb64-4378ea88a221.png)

**Comment by Yihanhu** [comment]
> Could you share your visualization script?

The visualization code is still being organized. This is the unorganized version, which can be used for now.
https://github.com/OpenDriveLab/UniAD/blob/prepare_for_release/tools/analysis_tools/visualize/run.py

**Comment by YTEP-ZHI** [comment]
I'm closing this issue as there's no further conversations, feel free to reopen it if needed @chasleslr.
