### ISSUE TITLE
How to only train perception tasks (tracker and map seg)

### ISSUE THREAD

**Issue by cherry-yh** [OpenDriveLab/UniAD#23]
Hi, if I just want to train tracker and map segmentation, which config should I use to reproduce your result? As far as I see, the perception part is trained only several epochs in the first stage, it seems that you can get an initial parameters, which might be further finetuned or optimized during the second e2e stage.
While in fact I do not want to do the e2e training, can you give me some advice on what should I do to only train the first stage and get a well result? 

More question, I see you have released the visualization code, could you tell me the command to do visualization?

Look forward to your reply, thanks.

**Comment by YTEP-ZHI** [comment]
You should use this command to train track+map module from scratch:   
`./tools/uniad_dist_train.sh ./projects/configs/stage1_track_map/base_track_map.py N_GPUS`

**Comment by YTEP-ZHI** [comment]
Hi, @cherry-yh. We add the visualization command here: https://github.com/OpenDriveLab/UniAD/blob/main/docs/TRAIN_EVAL.md#visualization-

**Comment by cherry-yh** [comment]
> 

Thanks for your reply. I have realized visualization according to your code, moreover, i comment the following part when visualizing map seg result since 'pts_bbox' info is removed while it is useful for map seg vis code.
`        if self.with_seg_head:
            result_seg =  self.seg_head.forward_test(bev_embed, gt_lane_labels, gt_lane_masks, img_metas, rescale)`

**Comment by YTEP-ZHI** [comment]
@cherry-yh  You probably need to comment these lines, where the 'pts_bbox' of map results are popped out. 
https://github.com/OpenDriveLab/UniAD/blob/3643c68f8305d1531057ef973df06c45a5de229b/projects/mmdet3d_plugin/uniad/detectors/uniad_e2e.py#L337-L338

**Comment by cherry-yh** [comment]
OK, thanks again for your quick reply. I temporarily close the issue, and reopen it when I have further two tasks joint training questions if necessary.

**Comment by cherry-yh** [comment]
OK, thanks again for your quick reply. I temporarily close the issue, and reopen it when I have further two tasks joint training questions if necessary.

**Comment by Alex-fishred** [comment]
I have commented result_seg[0] = pop_elem_in_result(result_seg[0], pop_list=['pts_bbox']) inside uniad_e2e.py
But during eval, the GPU RAM will keep increasing. How do you solve it?
![image](https://github.com/OpenDriveLab/UniAD/assets/76515591/aebc2e99-dd18-493a-8a00-f743e3c65cb7)
