### ISSUE TITLE
Frequently Asked & Good Questions

### ISSUE THREAD

**Issue by YTEP-ZHI** [OpenDriveLab/UniAD#26]
We will continually collect frequently asked questions and good questions in this thread.

## Good Questions
1. What do we think of the open-loop evaluation? Are open-loop results practical meaningful?  
We've answered this question from multiple perspectives to make it clarified: https://github.com/OpenDriveLab/UniAD/issues/29#issuecomment-1583070151

2. How to generate the ground-truth of occupancy prediction? Is the occupancy in UniAD the same with 3D occupacny? https://github.com/OpenDriveLab/UniAD/issues/36

**Comment by yihongXU** [comment]
Hi, great work! 

Could you provide few lines of code that can convert the motion outputs 'traj2eo' in global coordinates? It is a bit confusing in which coordinate system this "traj2ego" is. Thank you!
