### ISSUE TITLE
关于nuscenes_e2e_dataset.py中的旋转矩阵

### ISSUE THREAD

**Issue by chensiweiTHU** [OpenDriveLab/UniAD#27]
我正在另外一个数据集上实现uniad，但是我不是很确定自己是否正确理解了nuscenes_e2e_dataset.py 499行中的这段坐标变换关系。

        l2e_r = info['lidar2ego_rotation']
        l2e_t = info['lidar2ego_translation']
        e2g_r = info['ego2global_rotation']
        e2g_t = info['ego2global_translation']
        l2e_r_mat = Quaternion(l2e_r).rotation_matrix
        e2g_r_mat = Quaternion(e2g_r).rotation_matrix
        l2g_r_mat = l2e_r_mat.T @ e2g_r_mat.T
        l2g_t = l2e_t @ e2g_r_mat.T + e2g_t

如果l2e_r和l2e_t分别表示lidar到ego坐标系的坐标变换矩阵，其他的也以此类推，那lidar到global的坐标变换矩阵应该是由ego到global的变换矩阵左乘lidar到ego的坐标变换矩阵得到。因此根据我的理解，这段代码应该是：

       l2g_r_mat = e2g_r_mat @ l2e_r_mat
       l2g_t = e2g_r_mat@l2e_t + e2g_t

可以看出来，我求的旋转矩阵和你求的旋矩阵可能是转置（逆）的关系，请问这里对旋转矩阵求转置的原因是什么呢？

**Comment by YTEP-ZHI** [comment]
Nice catch @chensiweiTHU. The `l2g_r_mat` and `l2g_t` are used to update the reference points of a tracked agent in next frame, implemented in [velo_update](https://github.com/OpenDriveLab/UniAD/blob/7ae0fbf3eff77ad29849908f0043fd021713023b/projects/mmdet3d_plugin/uniad/detectors/uniad_track.py#L243).

Let me explain why the implemented `l2g_r_mat` is actually `l2g_r_mat.T` as you pointed out. Suppose we have `ref_pts` of shape [num_query, 4], `R1 = e2g_r_mat @ l2e_r_mat` of shape [4, 4]. 
Therefore, the rotated `ref_pts` should be: 
`out1 = R1 @ ref_pts.T`, `out1` is of shape [4, num_query]
However, we need to **transpose** `out1` to make it of shape [num_query, 4]. Therefore:
`ref_pts_rotated = out1.T = ref_pts @ R1.T = ref_pts @ (l2e_r_mat.T @ e2g_r_mat.T) = ref_pts @ R2`, where `ref_pts_rotated` is of shape [num_query, 4]

As explained, we simply set `l2g_r_mat = R2 =  e2g_r_mat @ l2e_r_mat`, and **post-multiply** it with ref_pts when rotating ref_pts, such as: 
https://github.com/OpenDriveLab/UniAD/blob/7ae0fbf3eff77ad29849908f0043fd021713023b/projects/mmdet3d_plugin/uniad/detectors/uniad_track.py#L279-L279

**Comment by YTEP-ZHI** [comment]
I'm closing this issue as it's resolved, feel free to reopen it if needed @chensiweiTHU.

**Comment by justeWang** [comment]
> 我正在另外一个数据集上实现uniad，但是我不是很确定自己是否正确理解了nuscenes_e2e_dataset.py 499行中的这段坐标变换关系。
> 
> ```
>     l2e_r = info['lidar2ego_rotation']
>     l2e_t = info['lidar2ego_translation']
>     e2g_r = info['ego2global_rotation']
>     e2g_t = info['ego2global_translation']
>     l2e_r_mat = Quaternion(l2e_r).rotation_matrix
>     e2g_r_mat = Quaternion(e2g_r).rotation_matrix
>     l2g_r_mat = l2e_r_mat.T @ e2g_r_mat.T
>     l2g_t = l2e_t @ e2g_r_mat.T + e2g_t
> ```
> 
> 如果l2e_r和l2e_t分别表示lidar到ego坐标系的坐标变换矩阵，其他的也以此类推，那lidar到global的坐标变换矩阵应该是由ego到global的变换矩阵左乘lidar到ego的坐标变换矩阵得到。因此根据我的理解，这段代码应该是：
> 
> ```
>    l2g_r_mat = e2g_r_mat @ l2e_r_mat
>    l2g_t = e2g_r_mat@l2e_t + e2g_t
> ```
> 
> 可以看出来，我求的旋转矩阵和你求的旋矩阵可能是转置（逆）的关系，请问这里对旋转矩阵求转置的原因是什么呢？

你好，请问您是如何在另外一个数据集上实现uniad的？目前看起来uniad和nuscenes数据集高度耦合，应该如何使用自定义或其他数据集？
