### ISSUE TITLE
planning head metric

### ISSUE THREAD

**Issue by xiaomeng9532** [OpenDriveLab/UniAD#30]
Hello, we downloaded your recent code and weight files and reproduced your results. Regarding the reproduced experimental results, we found significant discrepancies in the planning compared to the data provided in the paper. May I ask what is the reason for this?
![image](https://github.com/OpenDriveLab/UniAD/assets/30228848/61a053d1-306a-405e-84a6-81dd25b95af2)

**Comment by YTEP-ZHI** [comment]
Hi, @xiaomeng9532! Thanks for your interest. The discrepancies are mainly shown in L2-error metric (<0.1, in the first 3 columns of your table), while the overall reproduced collision rate is lower(better) than the reported result. We claim that we should focus on the collision rate as we value safety more than the imitation ability.

**Comment by YTEP-ZHI** [comment]
I'm closing this issue as there's no further conversation, feel free to reopen it if needed @xiaomeng9532 .
