### ISSUE TITLE
About detections

### ISSUE THREAD

**Issue by RomanticLeon** [OpenDriveLab/UniAD#37]
So cool, it's a great work!

From homepage demo video, I notice the model only detects vehicles. Does the end2end model also detect traffic lights and traffic signs?

**Comment by YTEP-ZHI** [comment]
Hi @RomanticLeon. Current version of uniad do not support traffic light/sign detection. It mainly detects dynamic agents (ped, car, truck, ...).

**Comment by YTEP-ZHI** [comment]
I'm closing this issue as there's no further conversation, feel free to reopen it if needed @RomanticLeon.
