### ISSUE TITLE
something wrong in visualizing

### ISSUE THREAD

**Issue by spring520** [OpenDriveLab/UniAD#39]
i first use
```bash
./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 8
```
and nothing went wrong 

then i want to use the visualize 
```bash
python ./tools/analysis_tools/visualize/run.py --predroot ./output/results.pkl --out_folder ./output_visualize --demo_video test_demo.avi --project_to_cam True
```
it goes 

```bash
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.426 seconds.

Reverse indexing ...
Done reverse indexing in 0.1 seconds.


Traceback (most recent call last):
  File "./tools/analysis_tools/visualize/run.py", line 342, in <module>
    main(args)
  File "./tools/analysis_tools/visualize/run.py", line 304, in main
    viser = Visualizer(version='v1.0-mini', predroot=args.predroot, dataroot='data/nuscenes', **render_cfg)
  File "./tools/analysis_tools/visualize/run.py", line 64, in __init__
    self.predictions = self._parse_predictions_multitask_pkl(predroot)
  File "./tools/analysis_tools/visualize/run.py", line 113, in _parse_predictions_multitask_pkl
    trajs = outputs[k][f'traj'].numpy()
KeyError: 'traj'
```

**Comment by Yihanhu** [comment]
This is because you only trained the Stage 1 model, so the model's output is limited to the perception part and does not include trajectory output. Try to set [https://github.com/OpenDriveLab/UniAD/blob/main/tools/analysis_tools/visualize/run.py#L292](url) to False.

**Comment by spring520** [comment]
it doesnt work. the error message is the same
must i train the model to use the visualize script? Or I can just download the checkpoints (uniad-based-e2e and uniad-based-track-map) and put it in the ckpt directory, since I dont have the compute resources to execute training.

**Comment by Yihanhu** [comment]
Yes, you can use the checkpoints. Did you try uniad-based-e2e?

**Comment by lswgh** [comment]
> Yes, you can use the checkpoints. Did you try uniad-base-e2e?

hi,i run the command:
./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth  2
or 
./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_e2e.pth  2
It's the same mistake:
![image](https://github.com/OpenDriveLab/UniAD/assets/58289826/12c2d955-7799-4d59-a70a-1cc570a489f1)

**Comment by spring520** [comment]
I have solved my problem by first eval the model using
```bash
./tools/uniad_dist_eval.sh ./projects/configs/stage2_e2e/base_e2e.py ./ckpts/uniad_base_e2e.pth 4
```

then using 
```bash
python ./tools/analysis_tools/visualize/run.py --predroot ./output/results.pkl --out_folder ./output_visualize --demo_video test_demo.avi --project_to_cam True
```
to visualize

**Comment by lswgh** [comment]
> I have solved my problem by first eval the model using
> 
> ```shell
> ./tools/uniad_dist_eval.sh ./projects/configs/stage2_e2e/base_e2e.py ./ckpts/uniad_base_e2e.pth 4
> ```
> 
> then using
> 
> ```shell
> python ./tools/analysis_tools/visualize/run.py --predroot ./output/results.pkl --out_folder ./output_visualize --demo_video test_demo.avi --project_to_cam True
> ```
> 
> to visualize
> 
> got the visualized inference result in output_visualize directory,

Thanks for your information.
