### ISSUE TITLE
About Planning Label

### ISSUE THREAD

**Issue by RuoyuChen10** [OpenDriveLab/UniAD#47]
Hi, thank you so much for your wonderful work. I would like to know where are the labels about the planning task, and the code snippet to evaluate the performance of the planning. Thanks!

**Comment by Yihanhu** [comment]
Hi @RuoyuChen10 Sorry for the messy code, 
these are the planning metrics, which is adopted from STP3.
https://github.com/OpenDriveLab/UniAD/blob/main/projects/mmdet3d_plugin/uniad/dense_heads/planning_head_plugin/planning_metrics.py

here is the planning label:
https://github.com/OpenDriveLab/UniAD/blob/main/projects/mmdet3d_plugin/datasets/data_utils/trajectory_api.py#L225
