### ISSUE TITLE
Can you list the environment configuration information for the algorithm to run?

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#51]
Can the environment configuration information be listed in readme.md in detail, I have encountered a lot of problems that caused the installation to fail due to inconsistent environments. 
Such as machine configuration, nvidia driver version number, operating system, etc.

**Comment by YTEP-ZHI** [comment]
@meua Hi, UniAD is mostly based on mmdet3d v0.17.1:https://github.com/open-mmlab/mmdetection3d/tree/v0.17.1, which requires compiling on gpu.  You can refer to their document for more information about installation. Once you have successfully installed the mmdet3d, the rest of packages required by UniAD are very easy to be installed.

**Comment by meua** [comment]
> @meua Hi, UniAD is mostly based on mmdet3d v0.17.1:https://github.com/open-mmlab/mmdetection3d/tree/v0.17.1, which requires compiling on gpu. You can refer to their document for more details about installation. Once you have successfully installed the mmdet3d, the rest of packages required by UniAD are very easy to be installed.

Hello, I would like to ask, whether the version of mmdet3d can be upgraded to v1.1.1, have you done a compatibility test?

**Comment by YTEP-ZHI** [comment]
@meua We may not upgrade the version of mmdet3d in a short period of time.  The coordinate system in mmdet3d v1.xxx is different with currently used version (v0.17.1). Thus it requires a lot of effort to align all the transformations in gt generation and visualization.

**Comment by meua** [comment]
understand, thank you for your explanation.
