### ISSUE TITLE
Map Element Inconsistency in UniAD Implementation

### ISSUE THREAD

**Issue by haibao-yu** [OpenDriveLab/UniAD#55]
Thank you for your efforts.

I have noticed a discrepancy regarding the map elements between the description in the paper and their implementation. According to the paper, the online map is categorized into four distinct elements: lanes, drivable areas, dividers, and pedestrian crossings. However, upon examining the code, it appears that the map elements from nuScenes are used instead, and they are classified into three classes: {0: ['road_divider', 'lane_divider'], 1: ['ped_crossing'], 2: ['road_segment', 'lane']}.

Could you please confirm if my understanding is accurate?

**Comment by ilnehc** [comment]
@haibao-yu Hi, I assume you are referring to this line of code: https://github.com/OpenDriveLab/UniAD/blob/94aa37fc03589dc2fa28679c87f321cbe63308ee/projects/mmdet3d_plugin/datasets/data_utils/vector_map.py#L53
The three categories are instance-wise modeled and vectorized. The drivable area information is obtained from nuScenes map here:
https://github.com/OpenDriveLab/UniAD/blob/94aa37fc03589dc2fa28679c87f321cbe63308ee/projects/mmdet3d_plugin/datasets/data_utils/data_utils.py#L169-L170
Sorry for the confusion.

**Comment by haibao-yu** [comment]
Thanks for your reply. You are right.
