### ISSUE TITLE
A question about traj loss

### ISSUE THREAD

**Issue by hangxu124** [OpenDriveLab/UniAD#59]
Hi, 
thanks for sharing your code! I'm reading your code and find
https://github.com/OpenDriveLab/UniAD/blob/05f63e628fe1d2b9dc1864cce5674635c7bbffc7/projects/mmdet3d_plugin/losses/traj_loss.py#L155, you add 1.8379 in NLL loss.
I know that a cls loss is needed here, but I have no idea where the -1.8379 come from.

Thanks again.

**Comment by Yihanhu** [comment]
It is just the normalizer for the gaussian distribution, which is ln(2*pi)

**Comment by DocAllen** [comment]
> ln(2*pi)
So that the GMM was not coded in projects, right?
