### ISSUE TITLE
Why not MapRT in MapFormer

### ISSUE THREAD

**Issue by yt7589** [OpenDriveLab/UniAD#6]
I noticed that in mapping task you used MapFormer which based on SegFormer. Your lab had MapTR to detect the lane, divider, crosswalk , etc. My question is why you choose to use SegFormer instead of MapTR?

**Comment by ilnehc** [comment]
Yes, replacing MapTR or other vectorized approaches is a promising way to improve mapping performance. It has been recently explored by the MapTR authors (https://arxiv.org/abs/2303.12077). 

:eyes: Actually I can provide you with another unofficial answer to your question. MapTR is released on Aug 30, which is after we started this project. And basically, we followed BEVFromer to do the mapping task, and we did not aim at getting the best result in the mapping module.
