### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.metrics'

### ISSUE THREAD

**Issue by yudefu** [OpenDriveLab/UniAD#60]
Hello author: Due to the version problem of the necessary software installed in the system, I cannot use pytorch-lightning well. After checking, I found that the lower version of pytorch-lightning no longer supports .metrics. And moved into torchtext, but it is not clear how to replace the code: several packages imported in C:\PycharmProjects\UniAD\projects\mmdet3d_plugin\uniad\dense_heads\occ_head_plugin/metrics.py;
Please help me out, thank you very much!

cuda：10.2
torch：1.13.0
torchtext：0.14.1
pytorch-lightning：1.9.4
ubuntu：20.0.4

**Comment by yudefu** [comment]
If I lower the version of pytorch-lightning（1.2.5）, it will trigger again:
 importerror: cannot import name 'batch' from 'torchtext.data'

**Comment by YTEP-ZHI** [comment]
@yudefu Please make sure your python version is 3.8.

**Comment by yudefu** [comment]
> @yudefu Please make sure your python version is 3.8.

Hello: My python environment is 3.9; I learned that pytorch_lightning.metrics has been abandoned in the higher version, even if I switch the local python environment to 3.8, it seems to be affected by pytorch-lightning, torchtext and other versions。
