### ISSUE TITLE
Ask a question？

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#65]
If I want to apply UniAD to Carla's control anyway, should I study the https://github.com/OpenDriveLab/ST-P3 project?

**Comment by ilnehc** [comment]
@meua Yes. You need a carla agent. Please refer to other projects such as [Transfuser](https://github.com/autonomousvision/transfuser).

**Comment by jiaxiaosong1002** [comment]
@meua Hi, we are the authors of Bench2Drive and we would like to introduce that we have implemented UniAD (non-official) in CARLA with code, checkpoints, and closed-loop results open sourced. Feel free to try it. https://github.com/Thinklab-SJTU/Bench2DriveZoo/tree/uniad/vad
