### ISSUE TITLE
Config for ablation experiment

### ISSUE THREAD

**Issue by AI-WangTao** [OpenDriveLab/UniAD#66]
I would like to reproduce the ablation experiment section of Uniad, as mentioned in the article. I would like to see the effects of track, map, motion, Occ, and plan, and how I should modify the configuration file.

**Comment by Yihanhu** [comment]
Hi @AI-WangTao, To fully reproduce the ablation requires some code modification. The currently open-sourced code does not include this, but you can implement it yourself. If you want to remove a certain module, then the passed query will become the preceding module. For example, if you remove the track query, then the agent query of the motion former will become the detection query, the same goes for motionformer and occformer.
