### ISSUE TITLE
Confusion regarding map queries setting

### ISSUE THREAD

**Issue by haibao-yu** [OpenDriveLab/UniAD#68]
Hello, I have some concerns regarding the map queries setting.

It seems that you exclusively utilize "things" queries for the downstream task. In that case, I'm curious why you incorporate additional "stuff" queries for semantic elements and subsequently output the drivable area. 

Have you considered exclusively employing "things" queries and outputting instance-wise map elements instead?

**Comment by ilnehc** [comment]
@haibao-yu In fact nothing particularly. We first had the drivable area prediction to compare with previous methods. Map is not our focus so we did not put too much attention on it and kept all the outputs.

**Comment by haibao-yu** [comment]
> @haibao-yu In fact nothing particularly. We first had the drivable area prediction to compare with previous methods. Map is not our focus so we did not put too much attention on it and kept all the outputs.

Thanks for your valuable response.
