### ISSUE TITLE
KeyError: 'bbox_results'

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#69]
Steps to reproduce the error:
```bash
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ ./tools/uniad_vis_result.sh
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 2.335 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======
Traceback (most recent call last):
  File "./tools/analysis_tools/visualize/run.py", line 340, in <module>
    main(args)
  File "./tools/analysis_tools/visualize/run.py", line 302, in main
    viser = Visualizer(version='v1.0-mini', predroot=args.predroot, dataroot='data/nuscenes', **render_cfg)
  File "./tools/analysis_tools/visualize/run.py", line 62, in __init__
    self.predictions = self._parse_predictions_multitask_pkl(predroot)
  File "./tools/analysis_tools/visualize/run.py", line 77, in _parse_predictions_multitask_pkl
    outputs = outputs['bbox_results']
KeyError: 'bbox_results'
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ 
```
The contents of the uniad_vis_result.sh file are as follows:
```bash
#!/bin/bash

python ./tools/analysis_tools/visualize/run.py \
    --predroot ./data/infos/nuscenes_infos_temporal_val.pkl \
    --out_folder ./data/visualize/output \
    --demo_video ./data/video/test.mp4 \
    --project_to_cam True
```

**Comment by beyondpzk** [comment]
predroot should be your results.pkl

**Comment by meua** [comment]
> predroot should be your results.pkl

Hello, can this official model not be used directly?
![image](https://github.com/OpenDriveLab/UniAD/assets/11570442/9cba4fac-1cbc-4df4-9732-1704c9f44309)

**Comment by ilnehc** [comment]
@meua These pkl files are for the full dataset, rather than the mini version. You need to generate on your own for the mini version.

> > predroot should be your results.pkl
> 
> Hello, can this official model not be used directly? ![image](https://user-images.githubusercontent.com/11570442/252543169-9cba4fac-1cbc-4df4-9732-1704c9f44309.png)

**Comment by meua** [comment]
> @meua These pkl files are for the full dataset, rather than the mini version. You need to generate on your own for the mini version.
> 
> > > predroot should be your results.pkl
> > 
> > 
> > Hello, can this official model not be used directly? ![image](https://user-images.githubusercontent.com/11570442/252543169-9cba4fac-1cbc-4df4-9732-1704c9f44309.png)

I have a mini data set, and a full data set, both. When visualizing, I choose to specify the data set？

**Comment by luiseia** [comment]
It will be generated after you run the uniad_dist_eval.sh file
