### ISSUE TITLE
KeyError: 'bbox_results'

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#70]
I use the model generated mini dataset by  myself, and still report the same error https://github.com/OpenDriveLab/UniAD/issues/69. I think it is a bug, not the approximate size of the model.
```bash
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ ./tools/uniad_vis_result.sh
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.288 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.0 seconds.
======
Traceback (most recent call last):
  File "./tools/analysis_tools/visualize/run.py", line 340, in <module>
    main(args)
  File "./tools/analysis_tools/visualize/run.py", line 302, in main
    viser = Visualizer(version='v1.0-mini', predroot=args.predroot, dataroot='data/nuscenes', **render_cfg)
  File "./tools/analysis_tools/visualize/run.py", line 62, in __init__
    self.predictions = self._parse_predictions_multitask_pkl(predroot)
  File "./tools/analysis_tools/visualize/run.py", line 77, in _parse_predictions_multitask_pkl
    outputs = outputs['bbox_results']
KeyError: 'bbox_results'
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ ll -trh ./data/infos/
total 1.2G
-rw-rw-r--  1 jarvis jarvis 986M 3月  25 01:19 nuscenes_infos_temporal_train.pkl.bak
-rw-rw-r--  1 jarvis jarvis 198M 3月  25 01:20 nuscenes_infos_temporal_val.pkl.bak
drwxrwxr-x 10 jarvis jarvis 4.0K 7月  10 13:48 ../
drwxrwxr-x  2 jarvis jarvis 4.0K 7月  11 13:48 ./
-rw-rw-r--  1 jarvis jarvis  17M 7月  11 13:49 nuscenes_infos_temporal_train.pkl
-rw-rw-r--  1 jarvis jarvis 5.1M 7月  11 13:50 nuscenes_infos_temporal_val.pkl
-rw-rw-r--  1 jarvis jarvis  12M 7月  11 13:51 nuscenes_infos_temporal_train_mono3d.coco.json
-rw-rw-r--  1 jarvis jarvis 3.8M 7月  11 13:51 nuscenes_infos_temporal_val_mono3d.coco.json
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ 
```
steps to reproduce:
1.`
 cd UniAD/data &&
mkdir infos &&
./tools/uniad_create_data.sh
`
2. `./tools/uniad_vis_result.sh`

The contents of the ./tools/uniad_create_data.sh file are as follows:
```bash

PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python tools/create_data.py nuscenes --root-path ./data/nuscenes \
       --out-dir ./data/infos \
       --extra-tag nuscenes \
       --version v1.0-mini \
       --canbus ./data/nuscenes
```

**Comment by ilnehc** [comment]
@meua 
- The `predroot` is `PATH_TO_YOUR_PREDICTION_RESULT_PKL` (path to your prediction result pkl).
- The generated infos are the formatted ground truth used for training.

No offense, but I recommend you start from some simple projects in mmdet and mmdet3d, to have an overview of the codebase and learn about the nuScenes dataset, etc.

**Comment by meua** [comment]
> @meua
> 
> * The `predroot` is `PATH_TO_YOUR_PREDICTION_RESULT_PKL` (path to your prediction result pkl).
> * The generated infos are the formatted ground truth used for training.
> 
> No offense, but I recommend you start from some simple projects in mmdet and mmdet3d, to have an overview of the codebase and learn about the nuScenes dataset, etc.

Excuse me, is the PATH_TO_YOUR_PREDICTION_RESULT_PKL file generated in this way?
![image](https://github.com/OpenDriveLab/UniAD/assets/11570442/8616780b-813c-4daa-905a-2bde125b6433)

**Comment by meua** [comment]
@ilnehc excuse me，using the v1.0-trainval dataset, I ran into the same problem:
```bash
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ ./tools/uniad_vis_result.sh
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 38.269 seconds.
======
Reverse indexing ...
Done reverse indexing in 3.4 seconds.
======
Traceback (most recent call last):
  File "./tools/analysis_tools/visualize/run.py", line 340, in <module>
    main(args)
  File "./tools/analysis_tools/visualize/run.py", line 302, in main
    viser = Visualizer(version='v1.0-trainval', predroot=args.predroot, dataroot='data/nuscenes', **render_cfg)
  File "./tools/analysis_tools/visualize/run.py", line 62, in __init__
    self.predictions = self._parse_predictions_multitask_pkl(predroot)
  File "./tools/analysis_tools/visualize/run.py", line 77, in _parse_predictions_multitask_pkl
    outputs = outputs['bbox_results']
KeyError: 'bbox_results'
(uniad38) jarvis@jia:~/coding/pyhome/github.com/meua/UniAD$ 
```

**Comment by ilnehc** [comment]
@meua 

> * The `predroot` is `PATH_TO_YOUR_PREDICTION_RESULT_PKL` (path to your prediction result pkl).
> * The generated infos are the formatted ground truth used for training.
> 
> No offense, but I recommend you start from some simple projects in mmdet and mmdet3d, to have an overview of the codebase and learn about the nuScenes dataset, etc.

- `uniad_create_data.sh` creates data info (eg `nuscenes_infos_temporal_train.pkl`) for training.
- PATH_TO_YOUR_PREDICTION_RESULT_PKL is generated when you do the evaluation (named `results.pkl` by default).
