### ISSUE TITLE
The test video test_demo.avi of Visualization

### ISSUE THREAD

**Issue by meua** [OpenDriveLab/UniAD#72]
Hello, can you provide the test video test_demo.avi of Visualization？
![image](https://github.com/OpenDriveLab/UniAD/assets/11570442/e0d70c3b-3a3b-42cc-ba68-62d8a9de8282)

**Comment by Yihanhu** [comment]
This is the argument for your output filename

**Comment by meua** [comment]
> This is the argument for your output filename

Ok, thank you for your guidance.
