### ISSUE TITLE
Visualization with predicted map

### ISSUE THREAD

**Issue by zengyf131** [OpenDriveLab/UniAD#74]
Hi, I am trying to visualize the map predicted by MapFormer, so I saved `result_seg[0]['pts_bbox']` into `result.pkl` during evaluation, and visualized the map with `render_cfg.with_map=True`.
This is one of the rendered images after I tweaked some colors.
![105](https://github.com/OpenDriveLab/UniAD/assets/102571077/c30a39c3-5f85-4218-9433-c1cf9cd7c965)
I believe the yellow part represents `dividers` and the purple part represents `crossings`. But my question is, does the green part represent `lanes` in `things`, or `drivable area` in `stuff`? And is there a way to visualize both `things` and `stuff`?
Also, I noticed there are `lane_score`, `score_list`, `stuff_score_list` and more in `result_seg[0]['pts_bbox']`, but I'm quite confused by the meaning of these results, so I would appreciate it if you could elaborate these results in the evaluation of MapFormer.

**Comment by Yihanhu** [comment]
Hi @zengyf131,
The green part represents the drivable area in 'stuff'. It's worth mentioning that 'stuff' only contains drivable areas, whereas 'things' includes lanes, dividers, crossings, and contours. I apologize for any confusion, allow me to clarify:
'lane_score' refers to the Bird's Eye View (BEV) confidence score map for 'things'.
'stuff_score_list' is the BEV confidence score map for 'stuff'.
'score_list' is a combination of both 'thing' and 'stuff' scores.

You can find all these definitions at: https://github.com/OpenDriveLab/UniAD/blob/cdf7b6d8e9730ec2eb0148ad97843fab9d24b8f3/projects/mmdet3d_plugin/uniad/dense_heads/panseg_head.py#L1301

**Comment by zengyf131** [comment]
Thanks for the clarification! 
However, I still have two questions left:
1. Is there way to visualize all components in 'things' and 'stuff', including lanes, dividers, crossings, contours, as well as drivable areas? The current method seems to visualize only dividers, crossings and drivable areas. 
2. I checked 'stuff_score_list' in the `result.pkl` after the evaluation, but I found that it was always an empty tensor. Is this normal or a bug?

**Comment by Yihanhu** [comment]
1. 'Contours' are the boundaries of the drivable area - they are fundamentally the same thing.
2. Thank you for your feedback, I will look into it.

**Comment by zengyf131** [comment]
Thanks, and what about 'lanes'? Is there a way to visualize 'lanes'?

**Comment by ilnehc** [comment]
@zengyf131 
https://github.com/OpenDriveLab/UniAD/blob/cdf7b6d8e9730ec2eb0148ad97843fab9d24b8f3/projects/mmdet3d_plugin/uniad/dense_heads/panseg_head.py#L1028-L1038
Lanes are basically the union of various vectorized elements. The definition of lanes here follows BEVFormer for comparison.
Note the difference compared to nusc' original definition. Its lanes and road_segment are contours in our setting. See some discussion in https://github.com/OpenDriveLab/UniAD/issues/55.

**Comment by zengyf131** [comment]
Got it. Thanks for the explanation!

**Comment by Alex-fishred** [comment]
@zengyf131 
I have commented result_seg[0] = pop_elem_in_result(result_seg[0], pop_list=['pts_bbox']) inside uniad_e2e.py
But during eval, the GPU RAM will keep increasing. How do you solve it?
![image](https://github.com/OpenDriveLab/UniAD/assets/76515591/65121471-1297-42d8-b4cb-15320044a936)

**Comment by zengyf131** [comment]
@Alex-fishred 
This happens because `result_seg[0]['pts_bbox']` is attached to the computation graph and it's on GPU side. What I did was detaching the values in this dict and moving it to the CPU side.
Basically something like this: 
```
for k, v in result_seg[0]['pts_bbox'].items():
    if isinstance(v, torch.Tensor):
        result_seg[0]['pts_bbox'][k] = v.detach().cpu()
```
But be aware that keeping `pts_bbox` might consume a lot of memory, in my case up to 80GB.

**Comment by Alex-fishred** [comment]
thank you for your reply
I have tried moving the Seg to the cpu and as a result the memory will grow as you said, I have tried freeing the memory but to no avail. In the end, I solved it by incompletely evaluating all Nuscenes data, but it didn't solve the problem itself.
I would like to ask, result_seg is the existing output of the model, why does it cause the GPU RAM to increase after saving it? Then why does the problem not occur when saving result_motion?
![image](https://github.com/OpenDriveLab/UniAD/assets/76515591/432ac97e-e6d7-4e0f-9b0d-8a704ff01d9b)

**Comment by zengyf131** [comment]
It could be a memory leak issue from PyTorch, but I am not really sure about the details. And I suspect `result_motion` is way smaller than `result_seg`, so saving `result_motion` isn't leading to a noticable memory leak (though it's still present). 
But to tackle this problem you could try increasing the virtual memory size in your OS. 100GB was enough in my case.

**Comment by zacharyzhang95** [comment]
> Hi, I am trying to visualize the map predicted by MapFormer, so I saved `result_seg[0]['pts_bbox']` into `result.pkl` during evaluation, and visualized the map with `render_cfg.with_map=True`. This is one of the rendered images after I tweaked some colors.

Hi @zengyf131 . Could you share your method for saving predicted map info into `result.pkl` ? I am also want to visualise predicted map segmentation in the output image. Thank you so much!

**Comment by zengyf131** [comment]
Hi @zacharyzhang95,
Saving this into `result.pkl` is quite simple. You just need to comment out the line `result_seg[0] = pop_elem_in_result(result_seg[0], pop_list=['pts_bbox', 'args_tuple'])` like what [Alex-fishred](https://github.com/Alex-fishred) did above. This line of code is in `/projects/mmdet3d_plugin/uniad/detectors/uniad_e2e.py`. But also be aware of the memory issue I mentioned above.

**Comment by zacharyzhang95** [comment]
> Hi @zacharyzhang95, Saving this into `result.pkl` is quite simple. You just need to comment out the line `result_seg[0] = pop_elem_in_result(result_seg[0], pop_list=['pts_bbox', 'args_tuple'])` like what [Alex-fishred](https://github.com/Alex-fishred) did above. This line of code is in `/projects/mmdet3d_plugin/uniad/detectors/uniad_e2e.py`. But also be aware of the memory issue I mentioned above.

Hi @zengyf131 . I'm very appreciate your support. It works now! When I evaluated it with nuScenes mini dataset, it cost me about 18G GPU memory and 48G system RAM. It is helpful to assign some virtual memory to the system.

**Comment by YANG-Deep** [comment]
Hi@zengyf131
Could you please tell me how to visulize the occformer?

I saved result[0]['occ'] into result.pkl during evaluation, and visualized the map with render_cfg.with_occ_map=True.
However, when I run the code, I find:

if 'topk_query_ins_segs' in outputs[k]['occ']:
 KeyError: 'occ'
Also when I search something named ['topk_query_ins_segs'], I found this code only occurred in /visualize/run.py
so I can not visualize the occupancy map correctly.

**Comment by zengyf131** [comment]
Hi @YANG-Deep,
I believe this error indicates that you did not successfully save `outputs[0]['occ']` in `result.pkl`. Therefore it says `KeyError: 'occ'`. 

I'm not sure what might cause this. Maybe you are running `stage1_track_map` instead of `stage2_e2e`? Also, you could check the result of occ_head by printing something during evaluation, for example in `projects/mmdet3d_plugin/uniad/detectors/uniad_e2e.py`.
