### ISSUE TITLE
Why does past trajectory include future trajectory?

### ISSUE THREAD

**Issue by xinshuoweng** [OpenDriveLab/UniAD#76]
Hi, 

Thanks for sharing the wonderful codebase! When looking at the trajectory_apy.py file, I noticed that the creation of past traj also includes future timestamps as in the following code

            fut_traj = np.zeros((self.predict_steps, 2))
            fut_traj_valid_mask = np.zeros((self.predict_steps, 2))
            past_traj = np.zeros((self.past_steps + self.fut_steps, 2))
            past_traj_valid_mask = np.zeros((self.past_steps + self.fut_steps, 2))

Would you mind explaining this?

Thanks!

**Comment by Yihanhu** [comment]
Great question! In order to better capture temporal information, we've integrated a small trajectory prediction network as a subtask of the regression branch into the Trackformer. Not only does it predict bounding boxes for tracklets, but it also predicts past and future trajectories.

**Comment by Yihanhu** [comment]
This part of the code is used to generate the ground truth for this supervision. Please forgive our odd naming convention. If fut_steps=0, it will only predict past trajectories.
