### ISSUE TITLE
Attention mask visualization?

### ISSUE THREAD

**Issue by wangsen1312** [OpenDriveLab/UniAD#78]
I am wondering how to render the attention mask such as figure 8 in supplementary part. which attn_mask is used in the visualization.

**Comment by Yihanhu** [comment]
Hi @wangsen1312 ,
We visualize the attn_mask over here:
https://github.com/OpenDriveLab/UniAD/blob/main/projects/mmdet3d_plugin/uniad/dense_heads/planning_head.py#L188C27-L188C38

**Comment by wangsen1312** [comment]
@Yihanhu Thank you for your quick response. But I found the the shape of plan_query is [1,1,256], which is weird, the attention mask should be [1, 25,256]?

**Comment by Yihanhu** [comment]
Yes, that is correct.

**Comment by wangsen1312** [comment]
@Yihanhu You mean the [1, 1, 256] is correct?

**Comment by Yihanhu** [comment]
Yes, the last dimension is channel, the attention mask should be like [1, 1, 40000], the last channel is H*W

**Comment by qiangt** [comment]
do you linear scale the attention mask to [0 255] or you use some non-linear function like log? There are many small values in the attention mask.

> Yes, the last dimension is channel, the attention mask should be like [1, 1, 40000], the last channel is H*W

**Comment by Yihanhu** [comment]
Yes, we normalized it by the max value.
