### ISSUE TITLE
Can't find the bin folder in gcc directory

### ISSUE THREAD

**Issue by TonyPeng-2018** [OpenDriveLab/UniAD#82]
I install gcc-5.4 by command " sudo apt-get install gcc-5", but  I can't find the bin folder under gcc installation path. 

Command "PATH=/mnt/gcc-5.4/bin" from INSTALL.md

Files in the directory: 
cc1            libasan_preinit.o  libgomp.so              libmpxwrappers.so
collect2       libasan.so         libgomp.spec            libquadmath.a
crtbegin.o     libatomic.a        libitm.a                libquadmath.so
crtbeginS.o    libatomic.so       libitm.so               libsanitizer.spec
crtbeginT.o    libbacktrace.a     libitm.spec             libssp_nonshared.a
crtend.o       libcc1.so          liblsan.a               libtsan.a
crtendS.o      libcilkrts.a       liblsan.so              libtsan.so
crtfastmath.o  libcilkrts.so      liblto_plugin.so        libubsan.a
crtprec32.o    libcilkrts.spec    liblto_plugin.so.0      libubsan.so
crtprec64.o    libgcc.a           liblto_plugin.so.0.0.0  lto1
crtprec80.o    libgcc_eh.a        libmpx.a                lto-wrapper
include        libgcc_s.so        libmpx.so               plugin
include-fixed  libgcov.a          libmpx.spec
libasan.a      libgomp.a          libmpxwrappers.a

**Comment by YTEP-ZHI** [comment]
@TonyPeng-2018  Try this in your activated conda environment:
`conda install -c omgarcia gcc-6`  
After installing, there's no need to manually export gcc path in this environment.

**Comment by TonyPeng-2018** [comment]
work, thank you.
