### ISSUE TITLE
Numpy incomptable issue

### ISSUE THREAD

**Issue by bzha5848** [OpenDriveLab/UniAD#84]
Hello here,

I'm currently having issues with training and evaluating code. I follow the installation guide and set the env, but when I was trying evaluating the data, I got error:
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 36672) of binary: /home/me/miniconda3/envs/uniad/bin/python

I don't know what's happening, but I suspect it might be incompatibility issues, as when I install the environment for UniAD I saw this error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
d2l 0.17.6 requires numpy==1.21.5, but you have numpy 1.24.4 which is incompatible.
onnx 1.12.0 requires protobuf<=3.20.1,>=3.12.2, but you have protobuf 4.23.4 which is incompatible.
mmdet3d 0.17.1 requires numpy<1.20.0, but you have numpy 1.24.4 which is incompatible.

Just wondering how to fix these errors?

Thanks so much!!

**Comment by TonyPeng-2018** [comment]
Same error!

**Comment by ilnehc** [comment]
@bzha5848 Hi, could you provide the full error log? The multiprocessing failure is sometimes caused by package import errors.

**Comment by YTEP-ZHI** [comment]
@bzha5848   Hi, seems that your numpy version is 1.24.4. You should install numpy==1.20.0, which is required by the evaluation of tracking, as is listed in https://github.com/OpenDriveLab/UniAD/blob/main/requirements.txt.

**Comment by bzha5848** [comment]
> @bzha5848 Hi, could you provide the full error log? The multiprocessing failure is sometimes caused by package import errors.

That's my error:
ImportError: numpy.core.multiarray failed to import

**Comment by YTEP-ZHI** [comment]
`ImportError: numpy.core.multiarray failed to import`
@bzha5848  As I mentioned, it's caused by incompatible numpy version. You should try to install numpy==1.20.0 .

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.`
Moreover, the dependency error could be simply ignored.

**Comment by wutianze** [comment]
I met another problem related to numpy:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mmdet3d 0.17.1 requires numpy<1.20.0, but you have numpy 1.20.0 which is incompatible.

Seems like the mmdet3d and UniAD use incompatible numpy

**Comment by thunguyenth** [comment]
@wutianze Hi, I got the same problem of numpy version incompatible between numpy==1.20.0 (in requirement.txt) and numpy<1.20.0 in mmdet3d). Did you solve this problem?

**Comment by wayneguo1002** [comment]
> @wutianze Hi, I got the same problem of numpy version incompatible between numpy==1.20.0 (in requirement.txt) and numpy<1.20.0 in mmdet3d). Did you solve this problem?
Same problem here, @wutianze @YTEP-ZHI. How could we fix this problem?

**Comment by thunguyenth** [comment]
@wayneguo1002 Hi, I remember that I solved this problem by changing the installation order of mmdet3d and numpy.
This is the order that I remember (as mentioned in the [Instaltion](https://github.com/OpenDriveLab/UniAD/blob/main/docs/INSTALL.md) guideline), if it doesn't work, then please try installing them in reverse order.
1. Install mmdet3d - [version: 0.17.1] - [build: dev_0] - [channel: < develop >]
2. Install numpy - [version: 1.20.0] - [build: pypi_0] - [channel: pypi]

I hope this helps.

**Comment by Feng-Shilong** [comment]
> @wutianze Hi, I got the same problem of numpy version incompatible between numpy==1.20.0 (in requirement.txt) and numpy<1.20.0 in mmdet3d). Did you solve this problem?

I also encountered the same problem, how should I solve it? @thunguyenth @wayneguo1002 @wutianze

**Comment by wayneguo1002** [comment]
> > @wutianze Hi, I got the same problem of numpy version incompatible between numpy==1.20.0 (in requirement.txt) and numpy<1.20.0 in mmdet3d). Did you solve this problem?
> 
> I also encountered the same problem, how should I solve it? @thunguyenth @wayneguo1002 @wutianze

According to my experience, you should use lower numpy version to meet the requirements of mmdet3d. Then you can install the required numpy version. For any package that requires a higher version of numpy than mmdet3d, you should install it after installing mmdet3d, because in my experience, the configuration instructions in the official documentation are not completely correct, at least not for everyone. Finally, check whether your various packages meet the requirements of the official configuration file.

**Comment by wayneguo1002** [comment]
> @wayneguo1002 Hi, I remember that I solved this problem by changing the installation order of mmdet3d and numpy. This is the order that I remember (as mentioned in the [Instaltion](https://github.com/OpenDriveLab/UniAD/blob/main/docs/INSTALL.md) guideline), if it doesn't work, then please try installing them in reverse order.
> 
> 1. Install mmdet3d - [version: 0.17.1] - [build: dev_0] - [channel: < develop >]
> 2. Install numpy - [version: 1.20.0] - [build: pypi_0] - [channel: pypi]
> 
> I hope this helps.

Thanks it helped a lot ^_^

**Comment by Feng-Shilong** [comment]
> > > @wutianze Hi, I got the same problem of numpy version incompatible between numpy==1.20.0 (in requirement.txt) and numpy<1.20.0 in mmdet3d). Did you solve this problem?
> > 
> > 
> > I also encountered the same problem, how should I solve it? @thunguyenth @wayneguo1002 @wutianze
> 
> According to my experience, you should use lower numpy version to meet the requirements of mmdet3d. Then you can install the required numpy version. For any package that requires a higher version of numpy than mmdet3d, you should install it after installing mmdet3d, because in my experience, the configuration instructions in the official documentation are not completely correct, at least not for everyone. Finally, check whether your various packages meet the requirements of the official configuration file.

Thanks, it helpes me a lot~
