### ISSUE TITLE
How to collect results from multiple GPUs? 

### ISSUE THREAD

**Issue by Christinepan881** [OpenDriveLab/UniAD#88]
Hello, thanks for your great work!

How do you collect results from multiple GPUs? I couldn't find the function to collect results from multi-rank. Would you please point out such function? Thanks!

**Comment by YTEP-ZHI** [comment]
@Christinepan881 Hi, you may refer to these functions:
https://github.com/OpenDriveLab/UniAD/blob/fa7fc3edc0811e1aff6dc952e38478a997c0843d/projects/mmdet3d_plugin/uniad/apis/test.py#L40  https://github.com/OpenDriveLab/UniAD/blob/fa7fc3edc0811e1aff6dc952e38478a997c0843d/projects/mmdet3d_plugin/uniad/apis/test.py#L191

**Comment by Christinepan881** [comment]
Thanks for your kind reply!
I'm also wondering the gt_bbox_3d format. Does the 9-D box in format of (center_x, center_y, center_z, width, height, depth, angle, velocity_x, velocity_y)? Then, if so, how to align the box on the (200, 200, 256) BEV map?
