### ISSUE TITLE
Could you please provide the script for generating Motion Anchors? Looking forward to your reply, thank you

### ISSUE THREAD

**Issue by EnginerPJ** [OpenDriveLab/UniAD#9]
Could you please provide the script for generating Motion Anchors? Looking forward to your reply, thank you

**Comment by Yihanhu** [comment]
The code is still being organized, but the method for generating anchors is actually quite simple, following these steps: 1. Extract all trajectories from the nuScenes dataset 2. Separate trajectories by category 3. Perform k-means clustering on the trajectories of each category (using sklearn.cluster.KMeans).

**Comment by foolhard** [comment]
Hi @Yihanhu 
I also have some questions about motion anchor file:
- How do you organize the trajectory information before clustering?
- I found the vector dims of each category anchor are` (6, 12, 2)`. What do these dims mean?
Thanks.

**Comment by YTEP-ZHI** [comment]
Dimensions of anchors:
* 6 is the number of output modalities or modes (multiple possible future)
* 12 is the number of prediction steps.
* 2 meaning xy

**Comment by foolhard** [comment]
Thanks for you clarification.

**Comment by Yihanhu** [comment]
please checkout at:
https://github.com/OpenDriveLab/UniAD/blob/prepare_for_release/tools/data_converter/create_anchor.py

**Comment by betterhalfwzm** [comment]
> please checkout at: https://github.com/OpenDriveLab/UniAD/blob/prepare_for_release/tools/data_converter/create_anchor.py

file does not exist
