### ISSUE TITLE
how to load checkpoints during training and the evaluation results are not very accurate

### ISSUE THREAD

**Issue by yudefu** [OpenDriveLab/UniAD#94]
Hello, I have two questions to ask you:
1、how to load checkpoints during training. I have looked at the parameter parsing and am not sure which parameter can control the loading breakpoint model to continue.

2、When I was conducting model evaluation, I found that the final result was consistent with the TRAIN_ Compared to EVAL.md, the result is not quite right. Could you please help me take a look;
Please take your busy schedule to receive your reply！

**Execute Command**：./tools/uniad_dist_eval.sh ./projects/configs/stage1_track_map/base_track_map.py ./ckpts/uniad_base_track_map.pth 3
**logs**：
[>>>>>>>>>>>>>>>>>>>>>>>>>>] 6021/6019, 2.2 task/s, elapsed: 2732s, ETA: 0s
writing results to output/results.pkl
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 110.0 task/s, elapsed: 55s, ETA: 0s
Results writes to test/base_track_map/Thu_Jul_27_10_16_23_2023/results_nusc.json
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 16.9 task/s, elapsed: 355s, ETA: 0s
Results writes to test/base_track_map/Thu_Jul_27_10_16_23_2023/results_nusc_det.json
Initializing nuScenes detection evaluation
Loaded results from test/base_track_map/Thu_Jul_27_10_16_23_2023/results_nusc_det.json. Found detections for 6019 samples.
Loading annotations for val split from nuScenes version: v1.0-trainval
100%|██████████| 6019/6019 [00:11<00:00, 518.29it/s]
Loaded ground truth annotations for 6019 samples.
Filtering predictions
=> Original number of boxes: 884914
=> After distance based filtering: 884570
=> After LIDAR and RADAR points based filtering: 884570
=> After bike rack filtering: 884214
Filtering ground truth annotations
=> Original number of boxes: 187528
=> After distance based filtering: 134565
=> After LIDAR and RADAR points based filtering: 121871
=> After bike rack filtering: 121861
Accumulating metric data...
Calculating metrics...
Saving metrics to: test/base_track_map/Thu_Jul_27_10_16_23_2023/det
mAP: 0.3816
mATE: 0.6842
mASE: 0.2748
mAOE: 0.3781
mAVE: 0.3919
mAAE: 0.2055
NDS: 0.4974
Eval time: 136.3s
![image](https://github.com/OpenDriveLab/UniAD/assets/39699204/2b3bb16e-4db9-4592-a795-30e1830c44b2)

======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 38.366 seconds.
======
Reverse indexing ...
Done reverse indexing in 9.6 seconds.
======
Initializing nuScenes tracking evaluation
Loaded results from test/base_track_map/Thu_Jul_27_10_16_23_2023/results_nusc.json. Found detections for 6019 samples.
Loading annotations for val split from nuScenes version: v1.0-trainval
100%|██████████| 6019/6019 [00:08<00:00, 677.14it/s]
Loaded ground truth annotations for 6019 samples.
Filtering tracks
=> Original number of boxes: 71415
=> After distance based filtering: 71412
=> After LIDAR and RADAR points based filtering: 71412
=> After bike rack filtering: 71355
Filtering ground truth tracks
=> Original number of boxes: 142261
=> After distance based filtering: 103564
=> After LIDAR and RADAR points based filtering: 93885
=> After bike rack filtering: 93875
Accumulating metric data...
Computing metrics for class bicycle...

Computed thresholds

Computing metrics for class bus...

Computed thresholds

Computing metrics for class car...

Computed thresholds

Computing metrics for class motorcycle...

Computed thresholds

Computing metrics for class pedestrian...

Computed thresholds

Computing metrics for class trailer...

Computed thresholds

Computing metrics for class truck...

Computed thresholds

Calculating metrics...
Saving metrics to: test/base_track_map/Thu_Jul_27_10_16_23_2023/track

### Final results ###

![Uploading image.png…]()

Aggregated results:
AMOTA 0.000
AMOTP 2.000
RECALL 0.000
MOTAR 0.000
GT 14556
MOTA 0.000
MOTP 2.000
MT 0
ML 6470
FAF 500.0
TP 0
FP 0
FN 101897
IDS 0
FRAG 0
TID 20.00
LGD 20.00
Eval time: 87.9s

**Comment by erwangccc** [comment]
Hi, @yudefu 
Your KPI is loss, have you solved this problem?

**Comment by FergusChan-cx** [comment]
Hi, do you solve this problem? I am faced with the same question, with total AMOTA 0.023
