### ISSUE TITLE
Difference between gt_sdc_fut_traj and sdc_planning?

### ISSUE THREAD

**Issue by pac2syv** [OpenDriveLab/UniAD#95]
Hi authors, what are the differences between gt_sdc_fut_traj and sdc_planning? I found that for the same sample, the values of the first 6 timesteps of these two tensors are different. But both are representing the future waypoints of the SDC, at the same timestep, shouldn't they have the same value?

**Comment by Yihanhu** [comment]
Hi @pac2syv ,
I believe these two should be the same; they are calculated with two different functions, but fundamentally represent the same thing, except that sdc_planning includes heading pose.
[https://github.com/OpenDriveLab/UniAD/blob/de91ab93df4029dc06ce98bd8f66187f7597ad7b/projects/mmdet3d_plugin/datasets/data_utils/trajectory_api.py#L225](url)
[https://github.com/OpenDriveLab/UniAD/blob/de91ab93df4029dc06ce98bd8f66187f7597ad7b/projects/mmdet3d_plugin/datasets/data_utils/trajectory_api.py#L180](url)

**Comment by pac2syv** [comment]
Thanks for your reply, but as you can see:
```
> /UniAD/projects/mmdet3d_plugin/uniad/detectors/uniad_e2e.py(209)forward_train()
-> losses = dict()
(Pdb) sdc_planning
tensor([[[[ 1.8797e-02,  3.3040e+00, -3.1456e+00],
          [ 3.2661e-02,  6.4289e+00, -3.1491e+00],
          [ 2.4354e-02,  9.2810e+00, -3.1514e+00],
          [ 1.5709e-02,  1.2461e+01, -3.1545e+00],
          [-2.8773e-03,  1.5963e+01, -3.1601e+00],
          [-4.6773e-02,  1.9074e+01, -3.1650e+00]]]], device='cuda:0',
       dtype=torch.float64)
(Pdb) gt_sdc_fut_traj
tensor([[[[ 1.3155e-02,  3.3123e+00],
          [ 1.7138e-02,  6.4365e+00],
          [ 1.4773e-02,  9.2869e+00],
          [ 1.4619e-03,  1.2476e+01],
          [-2.5316e-02,  1.5980e+01],
          [-6.9572e-02,  1.9094e+01],
          [-1.1470e-01,  2.1878e+01],
          [-1.7394e-01,  2.4930e+01],
          [-2.4454e-01,  2.8276e+01],
          [-3.1025e-01,  3.1278e+01],
          [-3.6969e-01,  3.4184e+01],
          [-4.5310e-01,  3.7116e+01]]]], device='cuda:0', dtype=torch.float64)
```

These are part of printed values, and their values are very different. Will this be a problem?

**Comment by Yihanhu** [comment]
I see, these differences might be due to the use of different calculation methods, but I don't think this is a big problem. These numbers are essentially the same, the fluctuations are within a reasonable range ~1 centimeter.
