### ISSUE TITLE
min_ADE、min_FDE、MR、EPA  ，How to view these result？

### ISSUE THREAD

**Issue by AI-WangTao** [OpenDriveLab/UniAD#98]
Thank you very much for the excellent code provided by the author. I am currently trying to reproduce this code. When I completed stage 2 training, it was difficult for me to find results in the log file that were the same as the detection indicators mentioned in the paper. For example: min_ ADE min_ FDE MR EPA. How can I see these indicators more intuitively

**Comment by Yihanhu** [comment]
Hi @AI-WangTao,
Could you share the log file?

**Comment by AI-WangTao** [comment]
Thank you very much for your reply.
I am attaching my training log here.
Thank you again for your help.
[20230727_192108.log](https://github.com/OpenDriveLab/UniAD/files/12246200/20230727_192108.log)
[train.07271920.txt](https://github.com/OpenDriveLab/UniAD/files/12246205/train.07271920.txt)

**Comment by Yihanhu** [comment]
![image](https://github.com/OpenDriveLab/UniAD/assets/33394567/2ae80067-3047-41da-a8f6-e7bfdf0995e0)
![image](https://github.com/OpenDriveLab/UniAD/assets/33394567/78e71d0a-cd4f-4d15-a5ec-5ceec2455404)
Sorry for the inconvenience, hope I have time to refactor this...
The first table is  min_ ADE min_ FDE MR, and the second table is for EPA

**Comment by hli2020** [comment]
> 

Welcome to contribute!

**Comment by AI-WangTao** [comment]
Thank you for your reply，
Can you write a calculation method for one of the indicators,
Is the overall indicator the average of all categories of indicators?
construction_vehicle,traffic_cone,barrier，Are these three categories involved in the calculation?

**Comment by Yihanhu** [comment]
For prediction metrics as you motioned above, only per class metric is provided. For detection & tracking metrics, the overall metric is the the average of all categories, such as mean AP.

**Comment by AI-WangTao** [comment]
We have validated the model you provided and obtained some results. As shown in the following image, I obtained an EPA value of 0.31 by calculating the average value. 
（0.4986+0.3199+0.2485+0.0664+0.3562+0.3749+0.3305）/ 7 = 0.31357
This is quite different from the 0.456 mentioned in the paper. May I ask if my EPA calculation method is incorrect? How to correct it to obtain an EPA similar to that in the article.
![image](https://github.com/OpenDriveLab/UniAD/assets/119799379/0b982b29-62ea-4420-b9c2-b79dc209553f)

**Comment by AI-WangTao** [comment]
Can the author help me answer the EPA calculation question above? Thank you very much!

**Comment by ilnehc** [comment]
@AI-WangTao Please scroll up further to see a merged result for mADE/EPA/etc. You can find that results are merged in two categories, ie car and pedestrian.

**Comment by SimonDoll** [comment]
Thanks a lot @Yihanhu  for the explanations but sadly I still do not understand how to compute a single indicator for EPA oder minADE / minFDE.
Is it simply the mean of the 7 tracking classes?
What does merged result for two classes mean, how is the merging done?
Thanks a lot for clarification!
